
SELECT X.NROEMPRESA, X.SEQPESSOA||' - '||G.NOMERAZAO FORNEC, X.NROTITULO, X.CODESPECIE,
       TO_CHAR(X.DTAVENCIMENTO,'DD/MM/YYYY') DTAVENCIMENTO, 
       DECODE(ABERTOQUITADO, 'A','ABERTO','Q','QUITADO') SITUACAO_TIT,
       DECODE(A.TIPOPAGAMENTO,
             'FOR','Fornecedores',
             'DIV','Diversos',
             'SAL','Salário',
              NULL) DESCTIPOPAGAMENTO, 
       DECODE(A.FORMAPAGAMENTO, 
             'CHQ','Cheque',
             'CCC','Credito em Conta',
             'CCO','Credito Conta Online',
             'DCC','DOC Compensação',
             'OPG','Ordem de Pagamento',
             'TDC','TED - CIP',
             'TDS','TED - STR') FORMAPAGAMENTO, 
       CASE WHEN B.SITUACAO = 'C' THEN 'CANCELADA'
            WHEN B.SITUACAO = 'P' THEN 'PAGA'
            WHEN B.SITUACAO = 'N' AND NVL(B.SEQENVIO,0) > 0 THEN 'ENVIADA'
            WHEN B.SITUACAO IS NULL THEN 'NÃO PROGRAMADA'
       ELSE 'PROGRAMADA' END SITUACAO_PAG
             
  FROM FI_TITULO X INNER JOIN FI_COMPLTITULO A ON A.SEQTITULO = X.SEQTITULO
                   INNER JOIN GE_PESSOA G      ON G.SEQPESSOA = X.SEQPESSOA
                    LEFT JOIN FI_PROGPAGAMENTO B ON B.SEQTITULO = X.SEQTITULO 
                    LEFT JOIN FI_CTACORRENTE FC ON FC.SEQCTACORRENTE = B.SEQCTACORRENTE 
                    LEFT JOIN FIV_FORNCONTAPESSOA FB ON FB.SEQPESSOA = X.SEQPESSOA AND FB.SITUACAO = 'A'
                    LEFT JOIN CONSINCO.FI_RETPAGTOELETR FR ON FR.SEQENVIO = B.SEQENVIO
                  
 WHERE X.DTAVENCIMENTO BETWEEN SYSDATE - 10 AND SYSDATE + 100 --:DT1 AND :DT2
   AND OBRIGDIREITO = 'O'
   
   AND (FORMAPAGAMENTO = 'CCC' AND FR.NROBANCO = 341 AND DESCRICAO NOT LIKE '%ITAU%'
    OR  FORMAPAGAMENTO = 'CCC' AND FR.NROBANCO = 237 AND DESCRICAO NOT LIKE '%BRAD%'
    OR  FORMAPAGAMENTO = 'CCC' AND FR.NROBANCO = 033 AND DESCRICAO NOT LIKE '%SANT%'
    
    OR B.SEQPROGRAMACAO IS NULL)
   
   AND FORMAPAGAMENTO IN ('CHQ',
                          'CCC',
                          'CCO',
                          'DCC',
                          'OPG',
                          'TDC')

   --AND X.NROEMPRESA IN (#LS1)
   
   AND X.CODESPECIE IN ('AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATIVEFU','COFINS','CRIPAG','CSSLL','DESP',
                        'DESPKM','DIVSOC','DUPP','DVRBEC','ENERGI','ESPORT','FATICD','FATNAG','FGTS','FGTSQT','FRETE','GNRE',
                        'ICMS','IMPOST','INSS','INSSNF','INTANG','IPI','IPTU','IR','IRRFFP','IRRFNF','ISSQN','ISSQNP','ISSST',
                        'LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS','RECARG','REEMB','RESCIS','RETSOC','SEGURO','SERVPJ','SUPERT','TEL','VLDESC')
   ORDER BY 1,2;
