CREATE OR REPLACE VIEW IMPV_METAS_DUP AS

SELECT LINHA, TO_CHAR("DATA",'DD/MM/YYYY') "DATA", NRO_EMPRESA, CATEGORIA_NIVEL_1, CATEGORIA_NIVEL_2, CATEGORIA_NIVEL_3, 
       TO_CHAR("META DE FATURAMENTO", 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') "META DE FATURAMENTO", 
       TO_CHAR("META DE LUCRATIVIDADE", 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') "META DE LUCRATIVIDADE",
        SEGMENTO

 FROM (

SELECT ROWNUM LINHA, TO_DATE(TRIM(X.DATA), 'DD/MM/YYYY')"DATA",
       TO_NUMBER(X.NRO_EMPRESA)       NRO_EMPRESA,
       CASE WHEN CATEGORIA_NIVEL_1 LIKE '%OUGUE'
            THEN 'AÇOUGUE'
            ELSE CATEGORIA_NIVEL_1 END CATEGORIA_NIVEL_1,
       X.CATEGORIA_NIVEL_2,
       X.CATEGORIA_NIVEL_3,
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')))
           ELSE 0 END "META DE FATURAMENTO",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')))
           ELSE 0 END "META DE LUCRATIVIDADE",

       X.SEGMENTO,
       ROW_NUMBER() OVER(PARTITION BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO
       ORDER BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO)  ODR

 FROM IMP_METAS X) XX

 WHERE ODR > 1
 
 ORDER BY 1;
