CREATE OR REPLACE VIEW IMPV_METAS AS

SELECT "DATA", NRO_EMPRESA, CATEGORIA_NIVEL_1, CATEGORIA_NIVEL_2, CATEGORIA_NIVEL_3, "META DE FATURAMENTO", "META DE LUCRATIVIDADE", "META DE MARGEM", "META DE PERDAS", SEGMENTO

 FROM (

SELECT TO_DATE(TRIM(X.DATA), 'DD/MM/YYYY')"DATA",
       TO_NUMBER(X.NRO_EMPRESA)       NRO_EMPRESA,
       CASE WHEN CATEGORIA_NIVEL_1 LIKE '%OUGUE'
            THEN 'AÇOUGUE'
            ELSE CATEGORIA_NIVEL_1 END CATEGORIA_NIVEL_1,
       X.CATEGORIA_NIVEL_2,
       X.CATEGORIA_NIVEL_3,
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE FATURAMENTO",'.',''), ',', '.')))
           ELSE 0 END "META DE FATURAMENTO",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE("META DE LUCRATIVIDADE",'.',''), ',', '.')))
           ELSE 0 END "META DE LUCRATIVIDADE",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE(REPLACE("META DE MARGEM",'.',''), '%',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE(REPLACE("META DE MARGEM",'.',''), '%',''), ',', '.')))
           ELSE 0 END "META DE MARGEM",
      CASE WHEN REGEXP_LIKE(TRIM(REPLACE(REPLACE(REPLACE(X."META DE PERDAS",'.',''), '%',''), ',', '.')), '^[0-9]+(\.[0-9]+)?$')
           THEN TO_NUMBER(TRIM(REPLACE(REPLACE(REPLACE(X."META DE PERDAS",'.',''), '%',''), ',', '.')))
           ELSE 0 END "META DE PERDAS",
       X.SEGMENTO,
       ROW_NUMBER() OVER(PARTITION BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO 
       ORDER BY X.DATA, X.NRO_EMPRESA, X.CATEGORIA_NIVEL_1, X.CATEGORIA_NIVEL_2, X.CATEGORIA_NIVEL_3, X.SEGMENTO)  ODR
       
 FROM IMP_METAS X) XX
 
 WHERE ODR = 1
 
