CREATE OR REPLACE VIEW CONSINCO.MAPV_APIPRECOPRODUTO AS
SELECT /*+ ORDERED */ 
  -- HINT Giuliano 30/10/24
  pkg_apiproduto.fmap_ApiCodAcesso(PROD.SEQPRODUTO) AS CODIGO_ACESSO_PRINCIPAL,
  PROD.SEQPRODUTO AS ID_PRODUTO,
  PROD.SEQFAMILIA AS ID_FAMILIA,
  PROD.SEQPRODUTOBASE AS ID_PRODUTO_BASE,
  EMP.NROCGC || LPAD(EMP.DIGCGC,2,0) CNPJ,
GREATEST(PRODEMPSEG.DTABASEEXPORTACAO,
         --  NVL(PROMOC.DTAHORAALTERACAO, '01-JAN-1900'), --- comentando por Cipolla 07/06/2024 problema API, data capa.
           NVL(PROMOC.DTAHORAALTERACAOITEM, '01-JAN-1900') ) DATA_ULTIMA_ATUALIZACAO,
  PROD.DESCCOMPLETA AS DESCRICAO_PRODUTO,
  PRODEMPSEG.STATUSVENDA AS STATUS_VENDA,
  FAM.FAMILIA AS DESCRICAO_FAMILIA,
  EMP.NROEMPRESA NUMERO_EMPRESA,
  PRODEMPSEG.NROSEGMENTO ID_SEGMENTO,
  EMP.NROSEGMENTOPRINC ID_SEGMENTO_PRINCIPAL,
  PRODEMPSEG.PRECOVALIDNORMAL AS PRECO_VENDA,
  PRODEMPSEG.QTDEMBALAGEM AS EMBALAGEM,
  COALESCE((SELECT PRECOVALIDNORMAL
              FROM MRL_PRODEMPSEG PRODEMPSEGCAIXA
             WHERE PRODEMPSEGCAIXA.SEQPRODUTO = PROD.SEQPRODUTO
               AND PRODEMPSEGCAIXA.NROSEGMENTO = EMPSEG.NROSEGMENTO
               AND PRODEMPSEGCAIXA.NROEMPRESA = EMP.NROEMPRESA
               AND PRODEMPSEGCAIXA.QTDEMBALAGEM = FAMDIV.PADRAOEMBCOMPRA
               AND PRODEMPSEGCAIXA.STATUSVENDA = 'A'
           ), ((PRODEMPSEG.PRECOVALIDNORMAL/PRODEMPSEG.QTDEMBALAGEM) * FAMDIV.PADRAOEMBCOMPRA)) PRECO_VENDA_CAIXA,
  FAMDIV.PADRAOEMBCOMPRA QTDE_CAIXA,
  PROMOC.DTAINICIO DATA_INICIO_PROMOCAO,
  PROMOC.DTAFIM DATA_FIM_PROMOCAO,
  PRODEMPSEG.PRECOVALIDPROMOC PRECO_PROMOCAO,
  FAMSEG.CLASSIFCOMERCABC CLASSIFICACAO_COMERCIAL,
  NVL(EMP.INDUSAAFV, 'N') USA_AFV
FROM MAP_PRODUTO PROD,
     MAX_EMPRESASEG EMPSEG,
     MAP_FAMILIA FAM,
     MAX_EMPRESA EMP,
     --MRL_PRODUTOEMPRESA PRODEMP,
     MRL_PRODEMPSEG PRODEMPSEG,
     MAD_FAMSEGMENTO FAMSEG,
     MAP_FAMDIVISAO FAMDIV,
     MAPV_APIPRECOPRODUTOPROMOC PROMOC
WHERE PROD.SEQFAMILIA = FAM.SEQFAMILIA
  AND PROD.SEQFAMILIA = FAMDIV.SEQFAMILIA
  --AND PRODEMP.NROEMPRESA = EMP.NROEMPRESA
  --AND PRODEMP.SEQPRODUTO = PROD.SEQPRODUTO
  AND PRODEMPSEG.SEQPRODUTO = PROD.SEQPRODUTO
  AND PRODEMPSEG.NROEMPRESA = EMP.NROEMPRESA
  AND PRODEMPSEG.NROSEGMENTO = EMPSEG.NROSEGMENTO
  AND PRODEMPSEG.QTDEMBALAGEM  = FAMSEG.PADRAOEMBVENDA
  AND FAMSEG.SEQFAMILIA = PROD.SEQFAMILIA
  AND EMP.NROEMPRESA = EMPSEG.NROEMPRESA
  AND EMP.NRODIVISAO = FAMDIV.NRODIVISAO
  AND EMPSEG.NROSEGMENTO = FAMSEG.NROSEGMENTO
  and PROMOC.SEQPRODUTO(+) = PRODEMPSEG.SEQPRODUTO
  and PROMOC.QTDEMBALAGEM(+) = PRODEMPSEG.QTDEMBALAGEM
  AND PROMOC.PRECOPROMOCIONAL(+) = PRODEMPSEG.PRECOVALIDPROMOC
  and PROMOC.NROEMPRESA(+) = PRODEMPSEG.NROEMPRESA
  and PROMOC.NROSEGMENTO(+) = PRODEMPSEG.NROSEGMENTO
  
;
