CREATE OR REPLACE FUNCTION CONSINCO.NAGF_BUSCAQTDITENSPROMOC_SM (psDta  IN NUMBER,
                                                                 psAno  IN NUMBER,
                                                                 psLOJA IN NUMBER,
                                                                 psSemana IN NUMBER) 
  RETURN NUMBER AS
  vsRetorno NUMBER(10);

BEGIN 
  

 SELECT MAX(ROWNUM) 
   INTO vsRetorno
   FROM (
 SELECT/*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
        DISTINCT A.SEQPROMOCAO,
       (SELECT COUNT(DISTINCT SEQPRODUTO) FROM MRL_PROMOCAOITEM B WHERE A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO) QTDITENS,
        DTAINICIO, DTAFIM, B.SEQPRODUTO

   FROM MRL_PROMOCAO A INNER JOIN MRL_PROMOCAOITEM B ON A.NROEMPRESA = B.NROEMPRESA  AND A.SEQPROMOCAO = B.SEQPROMOCAO AND A.CENTRALLOJA = B.CENTRALLOJA AND A.NROSEGMENTO = B.NROSEGMENTO

  WHERE EXTRACT (MONTH FROM DTAINICIO) =   psDta
    AND EXTRACT (MONTH FROM DTAFIM)    =   psDta

    AND EXTRACT (YEAR FROM DTAINICIO) =  psAno
    AND EXTRACT (YEAR FROM DTAFIM)    =  psAno

    AND A.NROEMPRESA = psLOJA
    AND B.STATUS != 'I'
    
    AND TRUNC((DTAINICIO - TRUNC(DTAINICIO, 'MM')) / 7) + 1 = psSemana);
    
    RETURN vsRetorno;

END;


