CREATE OR REPLACE FUNCTION NAGF_BUSCASTNAOCONTRIB (psSeqProduto IN CONSINCO.MAP_PRODUTO.SEQPRODUTO%TYPE,
                                                   psNroEmpresa IN CONSINCO.MAX_EMPRESA.NROEMPRESA%TYPE) 
  RETURN NUMBER IS
  vCST NUMBER(10);
  
BEGIN
  BEGIN
    
   SELECT X.SITUACAONF
     INTO vCST
     FROM CONSINCO.MAP_TRIBUTACAOUF X
    WHERE X.TIPTRIBUTACAO = 'SN' -- Saida Nao Contribuinte
      AND X.NROTRIBUTACAO = (SELECT NROTRIBUTACAO FROM MAP_FAMDIVISAO FD WHERE FD.SEQFAMILIA = (SELECT SEQFAMILIA FROM MAP_PRODUTO WHERE SEQPRODUTO = psSeqProduto))
      AND X.NROREGTRIBUTACAO = 0 -- Normal
      AND X.UFEMPRESA = (SELECT UF FROM MAX_EMPRESA MP WHERE MP.NROEMPRESA = psNroEmpresa)
      AND X.UFEMPRESA = X.UFCLIENTEFORNEC;
      
  
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      vCST := 000;
  END;

  RETURN vCST;
END;

