CREATE OR REPLACE FUNCTION CONSINCO.NAGF_DTAAUDITORIAITWORKS (codprod IN NUMBER)
       RETURN DATE IS
       DATA_ALT DATE;
       
       BEGIN
         SELECT MAX(DTAHORAUDITORIA) INTO DATA_ALT FROM MAP_AUDITORIA M WHERE M.SEQIDENTIFICA = codprod AND TABELA = 'MAP_PRODUTO'
                AND CAMPO NOT IN ('NOMEPRODUTOECOMM', 'DESCECOMMERCE');
                RETURN DATA_ALT;
                END;
