CREATE OR REPLACE FUNCTION CONSINCO.NAGF_BUSCACGCEMP (psEmpresa IN NUMBER)
RETURN VARCHAR2 AS
  vsRetorno NUMBER(8);
BEGIN
  SELECT SUBSTR(NROCGCCPF, 1, 8) INTO vsRetorno FROM GE_PESSOA WHERE SEQPESSOA = psEmpresa;
  RETURN vsRetorno;

END;
