FOR VT IN (
        SELECT A.SEQGERCOMPRA,
         A.NROEMPRESAGERALOTE
        FROM   CONSINCO.MAC_GERCOMPRA A
        WHERE  1=1
          AND  A.SITUACAOLOTE != 'C'
          AND  A.TIPOLOTE = 'T' AND
               -- TRATAMENTO PARA NÃO DUPLICAR EM EVENTUAL INTERRUPCAO DO JOB (DEVIDO A COMMITS)
               NOT EXISTS (SELECT 1 FROM CONSINCO.MAC_GERCOMPRA X
                           WHERE TRUNC(X.DTAHORINCLUSAO) = TRUNC(SYSDATE)
                           AND X.SEQGERCOMPORIGEM = A.SEQGERCOMPRA) AND
               --
               TRUNC(SYSDATE) BETWEEN A.DTAVALIDADEMODINI AND A.DTAVALIDADEMODFIM AND
               -- | Alt Giuliano
               -- | Não executa caso possua agendamento na semana
                   A.AGENDADOMINGO IS NULL
               AND A.AGENDASEGUNDA IS NULL
               AND A.AGENDATERCA   IS NULL
               AND A.AGENDAQUARTA  IS NULL
               AND A.AGENDAQUINTA  IS NULL
               AND A.AGENDASEXTA   IS NULL
               AND A.AGENDASABADO  IS NULL
               -- | Validação da Data - Puxa parametrização na NAGT_ABASTECIMENTOCONFIG
               AND A.SEQGERCOMPRA IN (SELECT SEQLOTEMODELO FROM CONSINCO.NAGV_BUSCADTAPEDIDO X WHERE X.DATA_VALIDA = TRUNC(SYSDATE))
           AND A.NROEMPRESAGERALOTE = NVL(PNNROEMPRESAABASTEC,A.NROEMPRESAGERALOTE) -- AJUSTE EMPRESA CONFORME SOLICITAÇÃO GIGA
           )
