CREATE OR REPLACE PROCEDURE CONSINCO.NAGP_EXPORTA_SPACEMAN_CATEG (v_CategN3 VARCHAR2(20))

AS

BEGIN
  
  FOR emp IN (SELECT NROEMPRESA FROM CONSINCO.MAX_EMPRESA WHERE NROEMPRESA < 100)
    
  LOOP
  
  CONSINCO.NAGP_EXPORTA_SPACEMAN(emp.NROEMPRESA, v_CategN3);
  
  COMMIT;
  
  END LOOP;
  
END;

-- Chamada na view C5:

EXECUTE CONSINCO.NAGP_EXPORTA_SPACEMAN_CATEG(:LS1);

SELECT 'Arquivos gerados com sucesso!' STATUS FROM DUAL
