CREATE OR REPLACE TRIGGER CONSINCO.NAGTR_TBI_ETIQUETAS
BEFORE INSERT
ON CONSINCO.MRLX_BASEETIQUETAPROD
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW

DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO CONSINCO.NAGT_CONTROLEIMPRESSAO (
        SEQPRODUTO,
        NROEMPRESA,
        DTAIMPRESSAO
    ) VALUES (
        :NEW.SEQPRODUTO,
        :NEW.NROEMPRESA,
        SYSDATE
    );

    COMMIT;
END;
