CREATE OR REPLACE VIEW CONSINCO.NAGV_PESSOAITWORKS_EX AS
(
-- Adicionado Fornec. UF EX na view

/* Select antigo na view dentro da consinco

    /*SELECT T.*
    FROM CONSINCO.NAGV_PESSOAITWORKS T
    WHERE T.RAZAO_SOCIAL <> ('CADASTRADO PELA LEITURA DO CAIXA')
        AND LPAD(T.CNPJCPF,14,0) = ((SELECT LPAD(ge.nrocgccpf,12,0)||LPAD(GE.DIGCGCCPF,2,0)
        FROM CONSINCO.GE_PESSOA GE WHERE GE.SEQPESSOA = :NR1));
  */


SELECT   GE.SEQPESSOA,--LPAD(GE.NROCGCCPF,12,0)||LPAD(GE.DIGCGCCPF,2,0) CNPJCPF -- -TICKET 17469 SOLICITAÇÃO SIRLENE
         --CASE WHEN GE.FISICAJURIDICA = 'F' THEN GE.NROCGCCPF||LPAD(GE.DIGCGCCPF,2,0) ELSE LPAD(GE.NROCGCCPF,12,0)||LPAD(GE.DIGCGCCPF,2,0) END CNPJCPF, -- TICKET 28250 SOLICITAÇÃO SIRLENE
           CASE WHEN GE.FISICAJURIDICA = 'F' THEN LPAD(GE.NROCGCCPF,9,0)||LPAD(GE.DIGCGCCPF,2,0) ELSE LPAD(GE.NROCGCCPF,12,0)||LPAD(GE.DIGCGCCPF,2,0) END CNPJCPF, -- TICKET 49294 SOLIC. SILENE 11/05/22
           GE.NOMERAZAO RAZAO_SOCIAL,
           GE.LOGRADOURO ENDERECO,
           GE.NROLOGRADOURO NUMERO,
           GE.BAIRRO BAIRRO,
           UPPER(CASE WHEN GE.FISICAJURIDICA = 'F' THEN 'SEM_IE' ELSE
                      CASE WHEN INSCRICAORG LIKE 'I %' OR UPPER(INSCRICAORG) = 'ISENTO' THEN 'ISENTO' ELSE
                        -- Tratativa para IE de acordo com regra SINTEGRA na tabela de/para
                        -- Ticket 230363 alterado em 25/10/2023 por Giuliano Gomes
                         CASE WHEN LENGTH(REGEXP_REPLACE(INSCRICAORG, '[^a-zA-Z0-9]', '', 1, 0)) <= IE.QTDDIG
                           THEN LPAD(REGEXP_REPLACE(INSCRICAORG, '[^a-zA-Z0-9]', '', 1, 0),IE.QTDDIG,0) ELSE REGEXP_REPLACE(INSCRICAORG, '[^a-zA-Z0-9]', '', 1, 0)
                            END END END ) IE_RG,
            --- TICKET 26437 ALTERAÇÃO 15/03/2022 CIPOLLA -- TICKET 48143 04/05/2022 CIPOLLA -- TICKET 65438 15/06/2022 *UPPER
           GE.CMPLTOLOGRADOURO COMPLEMENTO,
           GE.FONEDDD1|| GE.FONENRO1 DDD_FONE,
           GE.CIDADE CIDADE,
             (SELECT F.CODIBGE FROM CONSINCO.GE_CIDADE F WHERE F.SEQCIDADE = GE.SEQCIDADE) CODIGO_CIDADE,
           GE.PAIS PAIS,
               (SELECT F.CODPAIS FROM CONSINCO.GE_CIDADE F WHERE F.SEQCIDADE = GE.SEQCIDADE) CODIGO_PAIS,
           SUBSTR(REPLACE(GE.CEP,'-',''),0,8) CEP, -- ENVIAR APENAS 8 DÍGITOS - SOLIC SILENE 30/05/23
           GE.UF UF,
           -- TICKET 167818 - SOLICITAÇÃO SILENE - ALTERADO POR GIULIANO 09/01/23
           CASE WHEN GE.FISICAJURIDICA = 'J' THEN LPAD(GE.NROCPFPRODUTOR,9,0)||LPAD(GE.DIGCPFPRODUTOR,2,0)
                WHEN GE.FISICAJURIDICA = 'F' AND GE.INDPRODRURAL = 'S' THEN LPAD(GE.NROCGCCPF,9,0)||LPAD(GE.DIGCGCCPF,2,0) ELSE NULL END
                 CPFPRODUTORRURAL,
           CASE WHEN GE.INDPRODRURAL = 'S' THEN 'P' WHEN FR.TIPFORNECEDOR = 'D' THEN 'A' WHEN FR.TIPFORNECEDOR = 'I' THEN 'I' ELSE NULL END ATIV39ICMS, --- TICKET 51741 SOLICITAÇÃO DANI 17/05 - CIPOLLA
           NULL OPTANTESIMPLESNACIONALULTRAPASSALIMITE,
           FD.PERALIQICMSSIMPLESNAC OPTANTESIMPLESNACIONALALIQUOTAATUAL,
           NVL(GE.INDMICROEMPRESA,'N') MICROEMPRESA,
           GE.DTAINCLUSAO DTA_INCLUSAO,
           --NVL(GE.DTAALTERACAO,GE.DTAINCLUSAO ) DTA_ALTERACAO,
           -- TICKET 133606 - DANIELLE - 09/11/2022 - LEVAR DATA INCLUSAO QUANDO FOR LOJA E DATA ALTERACAO QUANDO FOR FORNECEDOR
           CASE WHEN GE.SEQPESSOA < 999 THEN GE.DTAINCLUSAO ELSE NVL(GE.DATAHORAALTERACAO,GE.DTAINCLUSAO) END DTA_ALTERACAO,

 --- ADICIONADO AS HORAS ABAIXO PARA TRATAR NO ROBO DA ITWORKS, PARA SINCRONIZAR TEM QUE TER HORA,
/*        CASE WHEN TO_CHAR(GE.DTAINCLUSAO,'hh24:mi:ss') = '00:00:00' THEN
                            TO_DATE(GE.DTAINCLUSAO,'DD/MM/RRRR') +  7/24  ELSE
                            GE.DTAINCLUSAO END DTA_INCLUSAO,
          CASE WHEN  TO_CHAR(NVL(GE.DTAALTERACAO,GE.DTAINCLUSAO ),'hh24:mi:ss') = '00:00:00' THEN
                                 TO_DATE(NVL(GE.DTAALTERACAO,GE.DTAINCLUSAO),'DD/MM/RRRR') +  7/24  ELSE
                             NVL(GE.DTAALTERACAO,GE.DTAINCLUSAO ) END DTA_ALTERACAO,*/
                             GE.SEQPESSOA COD_INTERNO,
           'View Nagumo' ORIGEM
FROM CONSINCO.GE_PESSOA GE  LEFT JOIN CONSINCO.MAF_FORNECEDOR FR ON (GE.SEQPESSOA = FR.SEQFORNECEDOR)
                            LEFT JOIN CONSINCO.MAF_FORNECDIVISAO FD ON GE.SEQPESSOA = FD.SEQFORNECEDOR
                            LEFT JOIN CONSINCO.NAGT_IESINTEGRA IE ON IE.UF = GE.UF -- Tabela de/para Regra IE SINTEGRA

WHERE (GE.NROCGCCPF IS NOT NULL OR GE.UF = 'EX')
AND GE.STATUS = 'A' --- SOLICITAÇÃO DANI TICKET 70625
)
;
