ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_49_VESTIMENTAS AS

-- Criado por Giuliano em 05/08/2024
-- Ticket 430626
-- Replica da base 49 - GMD - Com produtos da depara NAGT_DEPARA_VESTRH

SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/ V.NROEMPRESA LOJA_ORIGEM, V.SEQPESSOA LOJA_DESTINO,
       TO_CHAR(V.DTAVDA, 'YYYY') ANO, TO_CHAR(V.DTAVDA, 'MM') MES,
       V.DTAVDA DTAVDA,
       V.CODGERALOPER CGO,
       (SELECT Z.DESCRICAO
           FROM CONSINCO.MAX_CODGERALOPER Z
          WHERE Z.CODGERALOPER = V.CODGERALOPER) CGO_DESCRICAO, V.SEQPRODUTO,
       A.DESCCOMPLETA AS PRODUTO,
       SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / 1, 6)) AS QUANTIDADE,

       SUM((ROUND(V.VLRITEM, 2)) - (ROUND(V.VLRDEVOLITEM, 2) - (0))) AS VALOR,
      (SELECT DECODE(TIPO, 'E', 'EPI', 'U', 'UNIFORME') FROM CONSINCO.NAGT_DEPARA_VESTRH ZZ WHERE ZZ.SEQPRODUTO = V.SEQPRODUTO) TIPO

  FROM 
       CONSINCO.MAXV_ABCDISTRIBBASE_NAG_VEST V,
       CONSINCO.MAP_PRODUTO A

 WHERE V.SEQPRODUTO = A.SEQPRODUTO
   
   /* CRITERIOS PASSADOS NA MAXV_ABCDISTRIBBASE_NAG_VEST */

 GROUP BY V.NROEMPRESA, V.SEQPESSOA, TO_CHAR(V.DTAVDA, 'YYYY'),
          TO_CHAR(V.DTAVDA, 'MM'), V.CODGERALOPER, V.SEQPRODUTO,
          A.DESCCOMPLETA, DTAVDA

 ORDER BY 1, 2, 4, 5
;
