CREATE OR REPLACE VIEW CONSINCO.NAGV_INTEGRACAOECOMM_V3 AS
(
--- QUERY CRIADA POR CIPOLLA 13/10 INTEGRAÇÃO PREÇOS E ESTOQUE E-COMMERCE.
--- QUERY ANTIGA ESTAVA LEVANDO MAIS DE 50 MINUTOS.
--- VERIFICAR A INTEGRAÇÃO COM INFOPROC, PRECISA SER REVISTA, CUSTO MUITO ALTO
--- HINT ADICIONADO POR CIPOLLA EM 31/10/2022 - PERFORMANCE
--- ALTERADO A VIEW MADV_ESTOQUE_ECM PARA MADV_ESTOQUE_ECM_V2 EM 09/03/2023 SOLICITAÇÃO LEONARDO, PARA LEVAR A DATA DE ALTERAÇÃO DE MOVIMENTO DE ESTOQUE DOS PRODUTOS BASES.POR CIPOLLA.
--- ALTERADO A VIEW E INCLUIDO W.DTINICIO <= TRUNC(SYSDATE) ESTAVA SUBINDO OFERTAS FUTURAS PARA SITE, SOLICITAÇÃO LEONARDO EM 01/02/2024 POR CIPOLLA

--- Alterado por Giuliano em 30/07/2024 (Data Alteracao)

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       X.NROEMPRESA AS ID_LOJA,
       NVL(CASE WHEN Z.CATEGORIAN1 IS NULL THEN Z.CATEGORIAN2 ELSE Z.CATEGORIAN1 END,'--') AS DEPARTAMENTO,
       NVL(Z.CATEGORIAN2, '--') AS CATEGORIA,
       NVL(Z.CATEGORIAN3, '--') AS SUBCATEGORIA,
       NVL((SELECT M.MARCA FROM CONSINCO.MAP_MARCA M WHERE M.SEQMARCA = Y.SEQMARCA),'--') AS MARCA, 
      'UN' AS UNIDADE, '1UN' AS VOLUME,
       NVL(CONSINCO.FBUSCAEANECOMMERCEMIN(X.SEQPRODUTO),
       LPAD(X.SEQPRODUTO, 6, '0')) AS CODIGO_BARRA,
       INITCAP(Y.NOMEPRODUTO) AS NOME,
       TO_DATE(Y.DTAHORINCLUSAO, 'DD/MM/RRRR') AS DT_CADASTRO,
       --TO_DATE(Y.DTAHORALTERACAO, 'DD/MM/RRRR') AS DT_ULTIMA_ALTERACAO,
       TO_DATE(GREATEST(E.DTAHORULTMOVTOESTQ, 
                        Y.DTAHORALTERACAO,
                        CONSINCO.NAGF_BUSCAULTALTPRECO(X.SEQPRODUTO, X.NROEMPRESA, X.NROSEGMENTO, X.QTDEMBALAGEM)
                       ), 'DD/MM/RRRR') DT_ULTIMA_ALTERACAO,
       ROUND(ROUND(NVL(X.PRECOVALIDNORMAL, X.PRECOGERNORMAL) / X.QTDEMBALAGEM *
          X.QTDEMBALAGEM,
          2),
          2) VLR_PRODUTO,
       ROUND(ROUND(NVL(X.PRECOVALIDPROMOC, X.PRECOGERPROMOC) / X.QTDEMBALAGEM *
          X.QTDEMBALAGEM,
          2),
          2) VLR_PROMOCAO,
       ROUND(NVL(W.PRECOPPROMOCIONAL, 0), 2) PRECO_DOIS,
       CASE WHEN E.QTDESTOQUE < 0 THEN 0 ELSE E.QTDESTOQUE END AS QTD_ESTOQUE_ATUAL, 
       0 AS QTD_ESTOQUE_MINIMO,
       NVL(INITCAP(Y.BREVEDESCRICAO), '--') AS DESCRICAO, 1 AS ATIVO,
       Y.SEQPRODUTO AS PLU, 0 AS VLR_COMPRA, 'N' AS VALIDADE_PROXIMA,
       0 AS VLR_ATACADO, 0 AS QTD_ATACADO, Y.URLAMIGAVEL AS IMAGE_URL,
       Y.QTDMULTIPLOVDAECOMMERCE MULTIPLOECOMM, X.NROSEGMENTO
  
  FROM CONSINCO.MRL_PRODEMPSEG X
 INNER JOIN CONSINCO.MADV_PRODUTO_ECM Y
    ON (X.SEQPRODUTO = Y.SEQPRODUTO AND X.QTDEMBALAGEM = 1 AND
       X.NROSEGMENTO = 5)
  LEFT JOIN CONSINCO.ETLV_CATEGORIA Z
    ON (Z.SEQFAMILIA = Y.SEQFAMILIA AND Z.NRODIVISAO = 1)
  LEFT JOIN CONSINCO.MADV_ESTOQUE_ECM_V2 E
    ON (E.NROEMPRESA = X.NROEMPRESA AND E.SEQPRODUTO = Y.SEQPRODUTO)
  LEFT JOIN REMARCAPROMOCOES@INFOPROCMSSQL W
    ON (W.CODLOJA = X.NROEMPRESA AND
       LPAD(NVL(CONSINCO.FBUSCAEANECOMMERCEMIN(X.SEQPRODUTO),
                 LPAD(X.SEQPRODUTO, 6, '0')),
             14,
             0) = W.CODIGOPRODUTO AND W.DTFIM >= TRUNC(SYSDATE) AND
       W.DTINICIO <= TRUNC(SYSDATE))
 
 WHERE 1 = 1
   AND E.DTAHORULTMOVTOESTQ >= SYSDATE - 120 --- SOLICITAÇÃO LEONARDO EM 15/02/2023 PARA LEVAR APENAS OS PRODUTOS QUE TIVERAM MOVIMENTAÇÃO NOS ÚLTIMOS 90 DIAS.
   AND X.STATUSVENDA != 'I'
)
;
