CREATE OR REPLACE VIEW CONSINCO.NAGV_ECOMM_BASERELAC AS

-- Silene | Ecomm | Alt Integracao

SELECT X.SEQPRODUTO, X.DESCCOMPLETA, NVL(DECODE(X.INDINTEGRAECOMMERCE, 'S','SIM','N','NÃO'),'NÃO') INTEGRA_ECOMM,
                                     DECODE(PESAVEL, 'S','SIM','N','NAO') PESAVEL
  FROM MAP_PRODUTO X INNER JOIN MAP_FAMILIA Z ON X.SEQFAMILIA = Z.SEQFAMILIA

 WHERE X.DESCCOMPLETA LIKE '%CARN%PRAT%'
    OR EXISTS (SELECT 1 FROM NAGT_LISTA_PRODECOMM D WHERE D.SEQPRODUTO = X.SEQPRODUTO)

/*UNION ALL

SELECT C.CODACESSO EAN, B.SEQPRODUTO PLU, B.DESCCOMPLETA, NVL(DECODE(B.INDINTEGRAECOMMERCE, 'S','SIM','N','NÃO'),'NÃO') INTEGRA_ECOMM,
                                     DECODE(PESAVEL, 'S','SIM','N','NAO') PESAVEL
  FROM MAP_PRODUTO X INNER JOIN MAP_PRODUTO B ON B.SEQPRODUTO = X.SEQPRODUTOBASE
                     INNER JOIN MAP_FAMILIA Z ON B.SEQFAMILIA = Z.SEQFAMILIA
                      LEFT JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = B.SEQPRODUTO AND C.TIPCODIGO = 'E'

WHERE X.DESCCOMPLETA LIKE '%CARN%PRAT%'  */;
