CREATE OR REPLACE VIEW CONSINCO.NAGV_IMPNFEEMPINCORRETA AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ V.SEQNOTAFISCAL,
       V.NUMERONF,
       V.SERIENF,
       V.SEQPESSOA FORNEC,
       V.NOMERAZAO RAZAO,
       TO_DATE(V.DTAEMISSAO, 'DD-MM-YYYY') EMISSAO,
       V.NROEMPRESA EMP_CERTA, I.NROEMPRESA EMP_ERRADA,
       DTAEMISSAOC5

  FROM MRLV_NFEIMPORTACAO V INNER JOIN MRL_NFEIMPORTACAO I ON I.SEQNOTAFISCAL = V.SEQNOTAFISCAL

 WHERE 1=1

   AND V.NROEMPRESA != I.NROEMPRESA
   --AND V.SEQNOTAFISCAL = 23171107

   --AND DTAEMISSAOC5 BETWEEN DATE '2024-06-01' AND SYSDATE + 1

   AND NOT EXISTS
  (SELECT X.SEQNOTAFISCAL
          FROM MLF_AUXNOTAFISCAL X
         WHERE X.NUMERONF = V.NUMERONF
           AND X.SEQPESSOA = V.SEQPESSOA
           AND LPAD(TRIM(X.SERIENF), 3, '0') =
               LPAD(V.SERIENF, 3, '0')
           AND X.NROEMPRESA = V.NROEMPRESA
           AND X.TIPNOTAFISCAL = 'E'
           AND NVL(TO_CHAR(X.DTAEMISSAO, 'dd/mm/yyyy'),
                   V.DTAEMISSAO) =
               V.DTAEMISSAO
           AND NVL(X.NFECHAVEACESSO,
                   NVL(X.NFECHAVEACESSOCOPIA, V.CHAVEACESSO)) =
               V.CHAVEACESSO

        UNION

        SELECT XX.SEQNOTAFISCAL
          FROM MLF_AUXNOTAFISCAL XX, MAX_CODGERALOPER PP
         WHERE XX.NFREFERENCIANRO = V.NUMERONF
           AND XX.NFREFERENCIASERIE = V.SERIENF
           AND XX.SEQPESSOA = V.SEQPESSOA
           AND XX.NROEMPRESA = V.NROEMPRESA
           AND XX.TIPNOTAFISCAL = 'E'
           AND PP.CODGERALOPER = XX.CODGERALOPER
           AND PP.TIPUSO = 'E'
           AND PP.INDNFREFPRODRURAL = 'S'
           AND XX.STATUSNF != 'C'

        UNION

        SELECT ANF.SEQNOTAFISCAL
          FROM MLF_AUXNOTAFISCAL ANF, MAX_CODGERALOPER CGO
         WHERE ANF.CODGERALOPER = CGO.CODGERALOPER
           AND ANF.NFREFERENCIANRO = V.NUMERONF
           AND ANF.NFREFERENCIASERIE = V.SERIENF
           AND ANF.NROEMPRESA = V.NROEMPRESA
           AND ANF.SEQPESSOA = V.SEQPESSOA
           AND ANF.TIPNOTAFISCAL = 'E'
           AND CGO.TIPCGO = 'E'
           AND CGO.TIPUSO = 'E')
   AND NOT EXISTS
 (SELECT Y.SEQNOTAFISCAL
          FROM MLF_NOTAFISCAL Y
         WHERE Y.NUMERONF = V.NUMERONF
           AND Y.SEQPESSOA = V.SEQPESSOA
           AND LPAD(TRIM(Y.SERIENF), 3, '0') =
               LPAD(V.SERIENF, 3, '0')
           AND Y.NROEMPRESA = V.NROEMPRESA
           AND Y.TIPNOTAFISCAL = 'E'
           AND TO_CHAR(Y.DTAEMISSAO, 'dd/mm/yyyy') =
               V.DTAEMISSAO
           AND NVL(Y.NFECHAVEACESSO, 0) = V.CHAVEACESSO

        UNION

        SELECT YY.SEQNOTAFISCAL
          FROM MLF_NOTAFISCAL YY, MAX_CODGERALOPER PP
         WHERE YY.NFREFERENCIANRO = V.NUMERONF
           AND YY.NFREFERENCIASERIE = V.SERIENF
           AND YY.SEQPESSOA = V.SEQPESSOA
           AND YY.NROEMPRESA = V.NROEMPRESA
           AND YY.TIPNOTAFISCAL = 'E'
           AND TO_CHAR(YY.NFREFERENCIADTAEMISSAO, 'dd/mm/yyyy') =
               V.DTAEMISSAO
           AND NVL(YY.NFEREFERENCIACHAVE, 0) =
               V.CHAVEACESSO
           AND PP.CODGERALOPER = YY.CODGERALOPER
           AND PP.TIPUSO = 'E'
           AND PP.INDNFREFPRODRURAL = 'S'

        UNION

        SELECT NF.SEQNOTAFISCAL
          FROM MLF_NOTAFISCAL NF, MAX_CODGERALOPER CGO
         WHERE NF.CODGERALOPER = CGO.CODGERALOPER
           AND NF.NFREFERENCIANRO = V.NUMERONF
           AND NF.NFREFERENCIASERIE = V.SERIENF
           AND NF.NROEMPRESA = V.NROEMPRESA
           AND NF.SEQPESSOA = V.SEQPESSOA
           AND NF.TIPNOTAFISCAL = 'E'
           AND CGO.TIPCGO = 'E'
           AND CGO.TIPUSO = 'E')

   AND CODOPERMANIFESTDEST NOT IN ('210210', '210220')
   AND NOT EXISTS
 (SELECT 1
          FROM MFL_NFELOG
         WHERE MFL_NFELOG.DESCRICAO LIKE '%OPERA%N_O REALIZADA%'
           AND MFL_NFELOG.NFECHAVEACESSO = V.CHAVEACESSO)

 ORDER BY DTAEMISSAOC5, NUMERONF
;
