CREATE OR REPLACE VIEW CONSINCO.NAGV_SALDOLOCAL_CD AS
SELECT A.NROEMPRESA, A.SEQPRODUTO, A.ESTOQUE, A.SEQLOCAL, LOCAL

  FROM MRL_PRODLOCAL A INNER JOIN MRL_LOCAL B         ON A.SEQLOCAL = B.SEQLOCAL AND A.NROEMPRESA = B.NROEMPRESA
 WHERE 1=1
   AND ESTOQUE != 0
   AND TIPLOCAL = 'O'
   AND A.NROEMPRESA > 500

ORDER BY 4;
S
