ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW NAGV_VALIDCFOPCGOTRIB_CADFAM AS

-- Criado por Giuliano em 23/01/2025
-- Solic Fiscal - Ticket 522719
-- Utilizado na PKG_INCONSISTENCIAS > NAGP_INC_FAM_01

   /* Primeira Regra
   CST 060 e existe CFOP */
SELECT DISTINCT 1 SEQREGRA, F.SEQFAMILIA,
       'CFOP CGO Fora: '||CGO.CFOPESTADO||' Dentro: '||C.CFOPESTADO||' | Trib.: '||FD.NROTRIBUTACAO||' | CST: '||UF.SITUACAONF||' | CGO: '||C.CODGERALOPER MSG
  FROM MAP_FAMILIA F INNER JOIN MAP_FAMDIVISAO FD    ON FD.SEQFAMILIA    = F.SEQFAMILIA
                     INNER JOIN MAP_TRIBUTACAOUF UF  ON UF.NROTRIBUTACAO = FD.NROTRIBUTACAO
                      LEFT JOIN MAX_CODGERALCFOP C   ON C.NROTRIBUTACAO  = FD.NROTRIBUTACAO 
                      LEFT JOIN MAX_CODGERALOPER CGO ON CGO.CODGERALOPER = C.CODGERALOPER
                            
 WHERE 1=1
   
   AND UF.UFEMPRESA        IN ('SP','RJ')
   AND (UF.UFEMPRESA       = 'SP' AND C.CODGERALOPER IN (76, 810)
    OR  UF.UFEMPRESA       = 'RJ' AND C.CODGERALOPER IN (910))
   AND UF.TIPTRIBUTACAO    = 'SC'
   AND UF.NROREGTRIBUTACAO = 0
   AND UF.UFCLIENTEFORNEC  = UF.UFEMPRESA
   
   AND UF.SITUACAONF = '060'
   AND EXISTS (SELECT 1 FROM MAX_CODGERALCFOP CC    
                       WHERE CC.CFOPESTADO    IS NOT NULL
                         AND CC.CODGERALOPER  = C.CODGERALOPER
                         AND CC.NROTRIBUTACAO = FD.NROTRIBUTACAO)
                         
   /* Segunda Regra
   CST diferente de 060 e CFOP nao existe ou diferente*/
   
   UNION ALL

SELECT DISTINCT 2 SEQREGRA, F.SEQFAMILIA,
       'CFOP diferente ou não existe dentro do CGO '||CASE WHEN UF.UFEMPRESA = 'SP' THEN '76/810' WHEN UF.UFEMPRESA = 'RJ' THEN '910' END||
       ' | Trib.: '||FD.NROTRIBUTACAO MSG
  FROM MAP_FAMILIA F INNER JOIN MAP_FAMDIVISAO FD    ON FD.SEQFAMILIA    = F.SEQFAMILIA
                     INNER JOIN MAP_TRIBUTACAOUF UF  ON UF.NROTRIBUTACAO = FD.NROTRIBUTACAO
                            
 WHERE 1=1
   
   AND UF.UFEMPRESA        IN ('SP','RJ')
   AND UF.TIPTRIBUTACAO    = 'SC'
   AND UF.NROREGTRIBUTACAO = 0
   AND UF.UFCLIENTEFORNEC  = UF.UFEMPRESA
   
   AND UF.SITUACAONF != '060'
   AND NOT EXISTS (SELECT 1 FROM MAX_CODGERALCFOP CC INNER JOIN MAX_CODGERALOPER CGO ON CGO.CODGERALOPER = CC.CODGERALOPER
                           WHERE NVL(CC.CFOPESTADO,0) != NVL(CGO.CFOPESTADO,0)
                             AND (UF.UFEMPRESA         = 'SP' AND CC.CODGERALOPER IN (76, 810)
                              OR  UF.UFEMPRESA         = 'RJ' AND CC.CODGERALOPER IN (910))
                             AND CC.NROTRIBUTACAO      = FD.NROTRIBUTACAO);
       
   
