SELECT A.ID_UNICO_CLIENTE,
       A.DATA,
       A.LOJA,
       A.CUPONS,
       A.CATEGORIA_NIVEL_1,
       A.CATEGORIA_NIVEL_2,
       A.CATEGORIA_NIVEL_3,
       A.VLR_VENDA,
       A.LUCRATIVIDADE,
       A.QTD_ITENS,
       A.QTD_ITENS_DISTINTOS FROM NAGV_VDAIDENTIFICADA A WHERE A.DATAFLT BETWEEN :DT1 AND :DT2

CREATE OR REPLACE VIEW CONSINCO.NAGV_VDAIDENTIFICADA AS

SELECT REPLACE(RAWTOHEX(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT => UTL_RAW.CAST_TO_RAW(NVL(XX.IDPESSOA, 0)))),
       'CFCD208495D565EF66E7DFF9F98764DA','') ID_UNICO_CLIENTE, 
       TO_CHAR(XX.DATA, 'DD/MM/YYYY') DATA, 
       IDFILIAL LOJA, 
       COUNT(DISTINCT IDCUPOM) CUPONS,
       CATEGORIAN1 CATEGORIA_NIVEL_1, CATEGORIAN2 CATEGORIA_NIVEL_2, CATEGORIAN3 CATEGORIA_NIVEL_3,
       ROUND((SUM(VLROPERACAO) / SUM(XX.NUMQTDVENDIDA))* SUM(NUMQTDVENDIDA),2) VLR_VENDA,
       ROUND(SUM(VLROPERACAO) - SUM(XX.VIMPOSTOS),2) LUCRATIVIDADE,
       SUM(NUMQTDVENDIDA) QTD_ITENS,
       COUNT(DISTINCT IDPRODUTO) QTD_ITENS_DISTINTOS,
       DATA DATAFLT
       
  FROM (

SELECT CASE WHEN FISICAJURIDICA = 'FISICA' THEN LPAD(G.NROCPFCNPJ,11,0) WHEN G.FISICAJURIDICA = 'JURIDICA'  THEN LPAD(G.NROCPFCNPJ,14,0) ELSE LPAD(G.NROCPFCNPJ,11,0) END IDPESSOA,
       X.NROEMPRESA IDFILIAL,
       X.SEQNF IDCUPOM,
       X.SEQPRODUTO IDPRODUTO,
       TO_DATE(TO_CHAR(DTAOPERACAO, 'DD/MM/RRRR') || ' ' || HORAOPERACAO || ':' || MINUTOOPERACAO, 'DD/MM/RRRR HH24:MI') DATVENDA,
       QTDOPERACAO  NUMQTDVENDIDA,
       X.Vvlroperacaobruto + X.Vlracrescimo VLRPRECOVENDAUNITARIO,
       x.vlrdesconto VLRDESCONTOUNITARIO,
       X.VLROPERACAO - X.VVLRCTOLIQUIDO - X.VVLRIMPOSTOSAIDA - NVL( X.VLRDESPOPERACIONALITEM, 0 ) - X.VLRCOMISSAO- X.VLRVERBACOMPRA - X.VLRCALCIMPOSTOVDA VIMPOSTOS,
       X.VLROPERACAO VLROPERACAO,
       X.DTAOPERACAO DATA,
       CATEGORIAN1, CATEGORIAN2, C.CATEGORIAN3

  FROM FATO_VENDA@CONSINCODW X  INNER JOIN DIM_CLIENTE@CONSINCODW G ON G.SEQCLIENTE = X.SEQCLIENTE
                                INNER JOIN MAP_PRODUTO A ON A.SEQPRODUTO = X.SEQPRODUTO
                                INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = A.SEQFAMILIA

 WHERE 1=1
   AND X.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911)
   AND FISICAJURIDICA = 'FISICA'
   AND X.NROEMPRESA IN (55,57)/*
   AND DTAOPERACAO BETWEEN :DT1 AND :DT2*/) XX
   
GROUP BY XX.IDPESSOA,IDFILIAL, XX.DATVENDA, DATA, CATEGORIAN1, CATEGORIAN2, CATEGORIAN3;
