CREATE OR REPLACE VIEW CONSINCO.NAGV_DTAAUDITORIAITWORKS AS

SELECT MAX(DTAHORAUDITORIA) DATA_ALTERACAO, SEQIDENTIFICA SEQPRODUTO FROM CONSINCO.MAP_AUDITORIA M 
       WHERE TABELA IN ('MAP_PRODUTO', 'MRL_PRODEMPSEG', 'MRL_PRODUTOEMPRESA')
         AND CAMPO NOT IN ('NOMEPRODUTOECOMM', 'DESCECOMMERCE')

                GROUP BY SEQIDENTIFICA;
