CREATE OR REPLACE VIEW CONSINCO.NAGV_MONITORPDV_INTEGRACOES AS
SELECT 'Monitor - Total Pendente Importacao' EXPORTACAO_CARGA,
       COUNT(1) QTDE,
       MAX(DTAHOREMISSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_CONTROLEMOVIMENTO
 WHERE STATUS < 2
UNION ALL
SELECT 'Monitor - Total com Falha Importacao' EXPORTACAO_CARGA,
       COUNT(1) QTDE,
       MAX(DTAHOREMISSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_CONTROLEMOVIMENTO
 WHERE STATUS > 2
UNION ALL
SELECT 'Monitor - Total Integrado',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
       AND REPLICACAO IN ('F')
UNION ALL
SELECT 'ERP - Pendente Exportacao Hoje',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
       AND REPLICACAO IN ('P', 'S')
UNION ALL
SELECT 'ERP - Total Pendente Exportacao',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE REPLICACAO IN ('P', 'S')
UNION ALL
SELECT 'ERP - Total com Falha na Exportacao',
       COUNT(1) QTDE,
       MAX(DTAHORINCLUSAO) ULTDATAINCLUSAO
  FROM MONITORPDV.TB_DOCTO
 WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
       AND REPLICACAO IN ('E')
UNION ALL
SELECT 'ERP - Total Doc Integrado Hoje',
       COUNT(1) QTDE,
       MAX(DTAHORAINSERCAO) ULTDATAINCLUSAO
  FROM CONSINCO.MFL_DOCTOFISCAL A
 WHERE A.PDVORIGEM = 1
       AND A.APPORIGEM = 7
       AND A.DTAMOVIMENTO = TRUNC(SYSDATE)
UNION ALL
SELECT 'Ult Carga Preco Monitor', 1, MAX(A.DTAHORFINAL) DTAHOREMISSAO
  FROM MONITORPDV.TB_LOGCARGAMONITOR A
 WHERE A.TABELA = 'TB_PRODPRECO'
UNION ALL
SELECT 'Carga Preco PDV', COUNT(1) QTDE, MAX(A.DTAHOREMISSAO) DTAHOREMISSAO
  FROM MONITORPDV.TB_CONTROLECARGAPDV A
 WHERE A.TABELA = 'TB_PRODPRECO'
       AND STATUS < 2;
