CREATE OR REPLACE VIEW NAGV_VALID_CEST_CST AS

SELECT DISTINCT X.SEQFAMILIA 
  FROM MAP_FAMILIA X INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = X.SEQFAMILIA
                     INNER JOIN MAP_TRIBUTACAOUF U ON U.NROTRIBUTACAO = F.NROTRIBUTACAO
                            
 WHERE U.NROREGTRIBUTACAO = 0
   AND U.TIPTRIBUTACAO = 'SC'
   AND X.CODCEST IS NULL
   AND U.UFEMPRESA = U.UFCLIENTEFORNEC
   AND U.UFEMPRESA IN ('SP','RJ') 
   AND U.SITUACAONF = '060'
   
UNION 

SELECT DISTINCT X.SEQFAMILIA 
  FROM MAP_FAMILIA X INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = X.SEQFAMILIA
                     INNER JOIN MAP_TRIBUTACAOUF RJ ON RJ.NROTRIBUTACAO = F.NROTRIBUTACAO 
                                                   AND RJ.UFEMPRESA = 'SP' 
                                                   AND RJ.UFCLIENTEFORNEC = 'RJ'
                                                   AND RJ.NROREGTRIBUTACAO = 0
                                                   AND RJ.TIPTRIBUTACAO = 'SC'
                     INNER JOIN MAP_TRIBUTACAOUF SP ON SP.NROTRIBUTACAO = F.NROTRIBUTACAO 
                                                   AND SP.UFEMPRESA = 'SP' 
                                                   AND SP.UFCLIENTEFORNEC = 'SP'
                                                   AND SP.NROREGTRIBUTACAO = RJ.NROREGTRIBUTACAO
                                                   AND SP.TIPTRIBUTACAO = RJ.TIPTRIBUTACAO
 
 WHERE RJ.NROREGTRIBUTACAO = 0
   AND RJ.TIPTRIBUTACAO = 'SC'
   AND X.CODCEST IS NULL
   AND RJ.UFEMPRESA = RJ.UFCLIENTEFORNEC
   AND (SP.SITUACAONF  = '060' AND RJ.SITUACAONF != '060'
    OR  SP.SITUACAONF != '060' AND RJ.SITUACAONF  = '060')
