CREATE OR REPLACE VIEW CONSINCO.NAGV_PRODWMS AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/
       A.NROEMPRESA DEPOSITANTE,
       A.SEQPRODUTO PLU,
       A.DESCCOMPLETA DESCRICAO,
       A.DESCREDUZIDA,
       A.REFFABRICANTE,
       A.SEQFORNECEDOR COD_FORNEC,
       X.NOMERAZAO FORNEC,
       A.ADVARMAZENAGEM,
       A.QTDTOLARMAZPROD,
       A.PZOVALIDADEDIA,
       DECODE(A.CODTIPENDERECO, 'A',' ALTO','B','BAIXO','M','MEDIO','N','NORMAL') TIPENDERECO,
       AM.DESCRICAO ARMAZENAGEM,
       DECODE(A.TIPSEPARACAO, 'N','NORMAL','C','CONGELADO','F','FLV','L','LEVE','P','PERIGOSO') TIPSEPARACAO,
       M.EMBALAGEM||' - '||A.PADRAOEMBCOMPRA PADRAOEMBCOMPRA,
       V.EMBALAGEM||' - '||A.PADRAOEMBVENDA PADRAOEMBVENDA,
       DECODE(A.STATUSCOMPRA, 'A','ATIVO','I','INATIVO','S','SUSPENSO') STATUSCOMPRA,
       DECODE(A.STATUSVENDA, 'A','ATIVO','I','INATIVO') STATUSVENDA,
       A.EMTETIQUETA,
       A.PESAVEL,
       A.INDPROCFABRICACAO,
       A.SEQPRODUTOBASE PLU_BASE,
       A.QTDVOLGERAETQMASTER,
       BB.DESCDISTRIBLINHA,
       CC.DESCLINHASEPAR

  FROM MLO_PRODUTO A  LEFT JOIN GE_PESSOA X ON X.SEQPESSOA = A.SEQFORNECEDOR
                      LEFT JOIN MLO_ATRIBUTOFIXO AM ON AM.LISTA = A.TIPARMAZENAGEM AND AM.TIPATRIBUTOFIXO = 'TIPARMAZ'
                     INNER JOIN MLO_PRODEMBALAGEM M ON M.SEQPRODUTO = A.SEQPRODUTO AND M.NROEMPRESA = A.NROEMPRESA AND M.QTDEMBALAGEM = A.PADRAOEMBCOMPRA
                     INNER JOIN MLO_PRODEMBALAGEM V ON V.SEQPRODUTO = A.SEQPRODUTO AND V.NROEMPRESA = A.NROEMPRESA AND V.QTDEMBALAGEM = A.PADRAOEMBVENDA
                      LEFT JOIN MLO_PRODEMBWM AA    ON AA.CODDEPOSITANTE = A.NROEMPRESA AND AA.SEQPRODUTO = A.SEQPRODUTO AND AA.NROEMPRESA = A.NROEMPRESA
                      LEFT JOIN MLO_DISTRIBUICAOLINHA BB ON BB.CODDISTRIBLINHA = AA.CODDISTRIBLINHA AND BB.NROEMPRESA = AA.NROEMPRESA
                      LEFT JOIN MLO_LINHASEPARACAO CC ON CC.CODLINHASEPAR = AA.CODLINHASEPAR AND CC.NROEMPRESA = AA.NROEMPRESA  AND CC.CODDISTRIBLINHA = BB.CODDISTRIBLINHA

 WHERE A.NROEMPRESA BETWEEN 500 AND 599;
