ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_PEDCANC_WMS_SM AS

SELECT /*+NO_PUSH_PRED (MLOV_CONTROLEETQSORTEREXPED)*/
       DISTINCT X.DTAINCLUSAO, X.NROPEDVENDA, X.SEQPESSOA EMP_DESTINO,
       XI.STATUSITEM, XI.SEQPRODUTO, (XI.QTDPEDIDA - QTDCORTEWM) QTD_TIRAR, XI.QTDATENDIDA, P.QTDSOLICITADA, XI.QTDPEDIDA, XI.QTDCORTEWM,
       X.NROCARGA, X.NROEMPRESA, X.USUINCLUSAO, X.USUCANCELAMENTO, XI.USUCANCELAMENTO USUCANC_ITEM, P.USUCANCELAMENTO USU_CANCWMS
  FROM MAD_PEDVENDA X INNER JOIN MAD_PEDVENDAITEM XI ON XI.NROPEDVENDA = X.NROPEDVENDA AND XI.NROEMPRESA = X.NROEMPRESA
                      INNER JOIN MAX_EMPRESA      M  ON M.NROEMPRESA   = X.NROEMPRESA
                      INNER JOIN consinco.MLOV_CONTROLEETQSORTEREXPED P ON P.SEQPESSOA  = X.SEQPESSOA 
                                                                       AND P.NROCARGA   = X.NROCARGA
                                                                       AND P.SEQPRODUTO = XI.SEQPRODUTO
                             
 WHERE 1=1 
   AND SUBSTR(P.SITUACAOETIQUETA, 1, 250) = 'Cancelada'
   AND X.SITUACAOPED != 'C'
   AND X.NROEMPRESA > 500
   AND XI.QTDATENDIDA > 0
   AND X.DTAINCLUSAO > DATE '2024-07-01' 
-- AND (XI.QTDPEDIDA - QTDCORTEWM) = P.QTDSOLICITADA
-- AND XI.QTDCORTEWM = P.QTDSOLICITADA;
;

SELECT * FROM NAGV_PEDCANC_WMS_SM

