CREATE OR REPLACE VIEW CONSINCO.NAGV_ITWORKS_REINF_ALUGUELPF AS
SELECT /*Aluguel PF - Chamado 268634 - Amalia Petronilio | Criado por Giuliano em 03/08/2023*/
       DISTINCT X.NRONOTA, X.NROEMPRESA LOJA,TO_CHAR(X.DTAEMISSAO, 'DD/MM/YYYY') DTAEMISSAO,
       TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DTALANCTO, TO_CHAR(B.DTAVENCTO, 'DD/MM/YYYY') DTAVENCTO,
       A.NOMERAZAO RAZAO_SOCIAL, LPAD(A.NROCGCCPF,12,0)||LPAD(A.DIGCGCCPF,2,0) CNPJ, NULL COD_NAT_REND,
       C.CODRECEITA COD_DARF,
       TO_CHAR(X.VALOR, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VALOR_TOTAL,
       CODRECDARFIRRFPESFIS IRRF_FISICA, TO_CHAR(X.DTAVENCTOIRPESFIS, 'DD/MM/YYYY') DATA_VENCTO_IR,
       TO_CHAR(X.VLRIRPESFIS,  'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLRIR, X.OBSERVACAO

   FROM CONSINCO.OR_NFDESPESA X INNER JOIN CONSINCO.GE_PESSOA A ON A.SEQPESSOA = X.SEQPESSOA
                                INNER JOIN OR_NFVENCIMENTO    B ON X.SEQNOTA   = B.SEQNOTA AND X.NROEMPRESA = B.NROEMPRESA
                                INNER JOIN ORV_NFDIRF         C ON C.SEQNOTA   = X.SEQNOTA
 WHERE 1=1
   AND C.CODRECEITA = 3208
   AND X.SITUACAO = 'I'

   ORDER BY 1,4;
