ALTER SESSION SET CURRENT_SCHEMA = CONSINCO;

CREATE OR REPLACE VIEW CONSINCO.NAGV_APURACAO_SELLOUT_DIA AS

SELECT MRL_CUSTOVERBA.NROEMPRESA,
       MRL_CUSTOVERBA.NROEMPRESAACORDO,
       CASE
         WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
          'F'
         WHEN NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
          'G'
         ELSE
          'P'
       END FPG,
       CASE
         WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
          MAP_PRODUTO.SEQFAMILIA
         WHEN NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
          NULL
         ELSE
          MAP_PRODUTO.SEQPRODUTO
       END COD_FP,
       CASE
         WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
          MAP_FAMILIA.FAMILIA
         WHEN NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
          MRL_CUSTOVERBA.DESCRGRUPOPRODUTO || ' - ' ||
          TO_CHAR(MRL_CUSTOVERBA.SEQLOTE)
         ELSE
          MAP_PRODUTO.DESCCOMPLETA
       END DESCRICAO,
       MRL_CUSTOVERBA.DTAINICIAL,
       MRL_CUSTOVERBA.DTAFINAL,
       DECODE(NVL(PCTUNITVERBA, 0),
              0,
              VLRUNITVERBA + NVL(VLRUNITPISCOFINS, 0),
              0) VLR_UNIT_EMB,
       MRL_CUSTOVERBA.PCTUNITVERBA,
       MAP_FAMEMBALAGEM.EMBALAGEM || ' ' || MRL_CUSTOVERBA.QTDEMBALAGEM EMB,
       MRL_CUSTOVERBA.QTDEMBALAGEM QTD_EMB,
       MRL_CUSTOVERBA.QTDLIMITEVERBA QTD_LIMITE,
       CASE
         WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
          (SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
             FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
            WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.SEQLOTE = X.SEQLOTE
              AND C.NROEMPRESA = X.NROEMPRESA
              AND C.CENTRALLOJA = X.CENTRALLOJA
              AND C.SEQVERBA = X.SEQVERBA
              AND C.SEQPRODUTO = X.SEQPRODUTO) +
          (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
            WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQLOTE = X.SEQLOTE
              AND D.NROEMPRESA = X.NROEMPRESA
              AND D.CENTRALLOJA = X.CENTRALLOJA
              AND D.SEQVERBA = X.SEQVERBA
              AND D.SEQPRODUTO = X.SEQPRODUTO)
         WHEN NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
          (SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
             FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
            WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.SEQLOTE = X.SEQLOTE
              AND C.NROEMPRESA = X.NROEMPRESA
              AND C.CENTRALLOJA = X.CENTRALLOJA
              AND C.SEQVERBA = X.SEQVERBA
              AND C.SEQPRODUTO = X.SEQPRODUTO) +
          (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
            WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQLOTE = X.SEQLOTE
              AND D.NROEMPRESA = X.NROEMPRESA
              AND D.CENTRALLOJA = X.CENTRALLOJA
              AND D.SEQVERBA = X.SEQVERBA
              AND D.SEQPRODUTO = X.SEQPRODUTO)
         ELSE
          (SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
             FROM MRL_LECUSTOVERBA C
            WHERE C.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
              AND C.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
              AND C.SEQVERBA = MRL_CUSTOVERBA.SEQVERBA) +
          (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E
            WHERE D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
              AND D.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
              AND D.SEQVERBA = MRL_CUSTOVERBA.SEQVERBA)
       END AS QTDUTILIZADAVERBA,
       CASE
         WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
          (SELECT NVL(SUM(DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                                 0,
                                 C.QTDUTILIZADAVERBA,
                                 C.VLRAPURVERBAPCT)),
                      0)
             FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
            WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.SEQLOTE = X.SEQLOTE
              AND C.NROEMPRESA = X.NROEMPRESA
              AND C.CENTRALLOJA = X.CENTRALLOJA
              AND C.SEQVERBA = X.SEQVERBA
              AND C.SEQPRODUTO = X.SEQPRODUTO) +
          (SELECT NVL(SUM(DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                                 0,
                                 D.QTDUTILIZADAVERBA,
                                 D.VLRAPURVERBAPCT)),
                      0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
            WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQLOTE = X.SEQLOTE
              AND D.NROEMPRESA = X.NROEMPRESA
              AND D.CENTRALLOJA = X.CENTRALLOJA
              AND D.SEQVERBA = X.SEQVERBA
              AND D.SEQPRODUTO = X.SEQPRODUTO)
         WHEN NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
          (SELECT NVL(SUM(DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                                 0,
                                 C.QTDUTILIZADAVERBA,
                                 C.VLRAPURVERBAPCT)),
                      0)
             FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
            WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.SEQLOTE = X.SEQLOTE
              AND C.NROEMPRESA = X.NROEMPRESA
              AND C.CENTRALLOJA = X.CENTRALLOJA
              AND C.SEQVERBA = X.SEQVERBA
              AND C.SEQPRODUTO = X.SEQPRODUTO) +
          (SELECT NVL(SUM(DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                                 0,
                                 D.QTDUTILIZADAVERBA,
                                 D.VLRAPURVERBAPCT)),
                      0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
            WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQLOTE = X.SEQLOTE
              AND D.NROEMPRESA = X.NROEMPRESA
              AND D.CENTRALLOJA = X.CENTRALLOJA
              AND D.SEQVERBA = X.SEQVERBA
              AND D.SEQPRODUTO = X.SEQPRODUTO)
         ELSE
          (SELECT NVL(SUM(DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                                 0,
                                 C.QTDUTILIZADAVERBA,
                                 C.VLRAPURVERBAPCT)),
                      0)
             FROM MRL_LECUSTOVERBA C
            WHERE C.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
              AND C.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
              AND C.SEQVERBA = MRL_CUSTOVERBA.SEQVERBA) +
          (SELECT NVL(SUM(DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                                 0,
                                 D.QTDUTILIZADAVERBA,
                                 D.VLRAPURVERBAPCT)),
                      0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E
            WHERE D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
              AND D.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
              AND D.SEQVERBA = MRL_CUSTOVERBA.SEQVERBA)
       END * (DECODE(NVL(MRL_CUSTOVERBA.PCTUNITVERBA, 0),
                     0,
                     MRL_CUSTOVERBA.VLRUNITVERBA +
                     NVL(MRL_CUSTOVERBA.VLRUNITPISCOFINS, 0),
                     1)) AS VLRTOTALVERBA,
       ((SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
           FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
          WHERE C.SEQLOTE = X.SEQLOTE
            AND C.NROEMPRESA = X.NROEMPRESA
            AND C.CENTRALLOJA = X.CENTRALLOJA
            AND C.SEQVERBA = X.SEQVERBA
            AND C.SEQPRODUTO = X.SEQPRODUTO
            AND C.SEQAPURACAO > 0
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END) +
       (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
           FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
          WHERE D.NROPEDVENDA = E.NROPEDVENDA
            AND D.NROEMPRESA = E.NROEMPRESA
            AND D.SEQLOTE = X.SEQLOTE
            AND D.NROEMPRESA = X.NROEMPRESA
            AND D.CENTRALLOJA = X.CENTRALLOJA
            AND D.SEQVERBA = X.SEQVERBA
            AND D.SEQPRODUTO = X.SEQPRODUTO
            AND D.SEQAPURACAO > 0
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END)) AS QTDAPURADA,
       ((SELECT NVL(SUM(CASE
                          WHEN NVL(X.PCTUNITVERBA, 0) = 0 THEN
                           C.QTDUTILIZADAVERBA *
                           (X.VLRUNITVERBA + NVL(X.VLRUNITPISCOFINS, 0))
                          ELSE
                           C.VLRAPURVERBAPCT
                        END),
                    0)
           FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
          WHERE C.SEQLOTE = X.SEQLOTE
            AND C.NROEMPRESA = X.NROEMPRESA
            AND C.CENTRALLOJA = X.CENTRALLOJA
            AND C.SEQVERBA = X.SEQVERBA
            AND C.SEQPRODUTO = X.SEQPRODUTO
            AND C.SEQAPURACAO > 0
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END) +
       (SELECT NVL(SUM(CASE
                          WHEN NVL(X.PCTUNITVERBA, 0) = 0 THEN
                           D.QTDUTILIZADAVERBA *
                           (X.VLRUNITVERBA + NVL(X.VLRUNITPISCOFINS, 0))
                          ELSE
                           D.VLRAPURVERBAPCT
                        END),
                    0)
           FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
          WHERE D.NROPEDVENDA = E.NROPEDVENDA
            AND D.NROEMPRESA = E.NROEMPRESA
            AND D.SEQLOTE = X.SEQLOTE
            AND D.NROEMPRESA = X.NROEMPRESA
            AND D.CENTRALLOJA = X.CENTRALLOJA
            AND D.SEQVERBA = X.SEQVERBA
            AND D.SEQPRODUTO = X.SEQPRODUTO
            AND D.SEQAPURACAO > 0
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END)) AS VLRAPURADO,
       ((SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
           FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
          WHERE C.SEQLOTE = X.SEQLOTE
            AND C.NROEMPRESA = X.NROEMPRESA
            AND C.CENTRALLOJA = X.CENTRALLOJA
            AND C.SEQVERBA = X.SEQVERBA
            AND C.SEQPRODUTO = X.SEQPRODUTO
            AND C.SEQAPURACAO IS NULL
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END) +
       (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
           FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
          WHERE D.NROPEDVENDA = E.NROPEDVENDA
            AND D.NROEMPRESA = E.NROEMPRESA
            AND D.SEQLOTE = X.SEQLOTE
            AND D.NROEMPRESA = X.NROEMPRESA
            AND D.CENTRALLOJA = X.CENTRALLOJA
            AND D.SEQVERBA = X.SEQVERBA
            AND D.SEQPRODUTO = X.SEQPRODUTO
            AND D.SEQAPURACAO IS NULL
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END)) AS QTDAAPURAR,
       ((SELECT NVL(SUM(CASE
                          WHEN NVL(X.PCTUNITVERBA, 0) = 0 THEN
                           C.QTDUTILIZADAVERBA *
                           (X.VLRUNITVERBA + NVL(X.VLRUNITPISCOFINS, 0))
                          ELSE
                           C.VLRAPURVERBAPCT
                        END),
                    0)
           FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
          WHERE C.SEQLOTE = X.SEQLOTE
            AND C.NROEMPRESA = X.NROEMPRESA
            AND C.CENTRALLOJA = X.CENTRALLOJA
            AND C.SEQVERBA = X.SEQVERBA
            AND C.SEQPRODUTO = X.SEQPRODUTO
            AND C.SEQAPURACAO IS NULL
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END) +
       (SELECT NVL(SUM(CASE
                          WHEN NVL(X.PCTUNITVERBA, 0) = 0 THEN
                           D.QTDUTILIZADAVERBA *
                           (X.VLRUNITVERBA + NVL(X.VLRUNITPISCOFINS, 0))
                          ELSE
                           D.VLRAPURVERBAPCT
                        END),
                    0)
           FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
          WHERE D.NROPEDVENDA = E.NROPEDVENDA
            AND D.NROEMPRESA = E.NROEMPRESA
            AND D.SEQLOTE = X.SEQLOTE
            AND D.NROEMPRESA = X.NROEMPRESA
            AND D.CENTRALLOJA = X.CENTRALLOJA
            AND D.SEQVERBA = X.SEQVERBA
            AND D.SEQPRODUTO = X.SEQPRODUTO
            AND D.SEQAPURACAO IS NULL
               
            AND X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND X.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
            AND NVL(X.SEQLOTEFAMILIA, 0) = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
                   MRL_CUSTOVERBA.SEQLOTEFAMILIA
                  ELSE
                   NVL(X.SEQLOTEFAMILIA, 0)
                END
            AND X.SEQPRODUTO = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQPRODUTO
                  ELSE
                   X.SEQPRODUTO
                END
            AND X.SEQVERBA = CASE
                  WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'N' AND
                       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'N' THEN
                   MRL_CUSTOVERBA.SEQVERBA
                  ELSE
                   X.SEQVERBA
                END)) AS VLRAAPURAR,
       MRL_CUSTOVERBA.SEQFORNECEDOR,
       GE_PESSOA.NOMERAZAO,
       MRL_CUSTOVERBA.SEQCOMPRADOR,
       MAX_COMPRADOR.APELIDO,
       (SELECT A.CODTIPOACORDOACRESC
          FROM MAX_EMPRESA_TIPOACORDOACRESC A
         WHERE A.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
           AND A.NROPERCTIPOACORDOACRESC =
               (SELECT MIN(B.NROPERCTIPOACORDOACRESC)
                  FROM MAX_EMPRESA_TIPOACORDOACRESC B
                 WHERE B.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA)) X,
       MAX_EMPRESA.NRODIVISAO,
       MRL_CUSTOVERBA.SEQVERBA,
       MRL_CUSTOVERBA.CENTRALLOJA,
       NVL(MAX_EMPRESA.CODTIPOACPROMOC_SELLOUT, MAX_EMPRESA.CODTIPOACPROMOC) X2,
       MRL_CUSTOVERBA.OBSERVACAO,
       MAP_PRODUTO.SEQFAMILIA,
       MRL_CUSTOVERBA.CODIGOVERBA,
       NVL(MRL_CUSTOVERBA.INDTIPACORDO, 'R') X3,
       MAP_PRODUTO.SEQPRODUTO,
       NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') X4,
       NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') X5,
       MRL_CUSTOVERBA.SEQLOTEFAMILIA,
       MRL_CUSTOVERBA.SEQLOTE,
       MRL_CUSTOVERBA.QTDUTILIZADAVERBA QTDUTIL,
       NVL(MRL_CUSTOVERBA.INDVERBACOMPART, 'N') X6
  FROM MRL_CUSTOVERBA,
       MAP_PRODUTO,
       MAP_FAMEMBALAGEM,
       MAX_EMPRESA,
       GE_PESSOA,
       MAX_COMPRADOR,
       MAP_FAMILIA

 WHERE MAP_PRODUTO.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
   AND MAP_FAMEMBALAGEM.SEQFAMILIA = MAP_PRODUTO.SEQFAMILIA
   AND MAP_FAMEMBALAGEM.QTDEMBALAGEM = MRL_CUSTOVERBA.QTDEMBALAGEM
   AND MAX_EMPRESA.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
   AND GE_PESSOA.SEQPESSOA = MRL_CUSTOVERBA.SEQFORNECEDOR
   AND MAX_COMPRADOR.SEQCOMPRADOR = MRL_CUSTOVERBA.SEQCOMPRADOR
   AND MAP_FAMILIA.SEQFAMILIA = MAP_PRODUTO.SEQFAMILIA
   AND MRL_CUSTOVERBA.NROACORDO IS NULL
   AND MRL_CUSTOVERBA.NROEMPRESAACORDO IS NULL
   AND MRL_CUSTOVERBA.INDVERBASEMACORDO = 'S'
   AND NVL(MRL_CUSTOVERBA.INDVERBAAPURADA, 'N') IN ('N', 'P')
      
   AND (MRL_CUSTOVERBA.STATUSVERBA = 'A' OR
       (MRL_CUSTOVERBA.STATUSVERBA = 'I' AND
       MRL_CUSTOVERBA.QTDUTILIZADAVERBA > 0 AND
       MRL_CUSTOVERBA.NROACORDO IS NULL))
   AND (MRL_CUSTOVERBA.ORIGEMVERBA NOT IN ('R', 'D', 'T') OR
       MRL_CUSTOVERBA.ORIGEMVERBA IS NULL)
   AND MRL_CUSTOVERBA.SEQPRODUTO IN
       (CASE WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
        (SELECT NVL(MAX(X.SEQPRODUTO), 0)
           FROM MRL_CUSTOVERBA X
          WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND ((NULL IS NULL) OR (NULL IS NOT NULL AND
                X.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO))) WHEN
        NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
        (SELECT NVL(MAX(X.SEQPRODUTO), 0)
           FROM MRL_CUSTOVERBA X
          WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
            AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
            AND ((NULL IS NULL) OR (NULL IS NOT NULL AND
                X.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO))) ELSE
        MRL_CUSTOVERBA.SEQPRODUTO END)
      
   AND MRL_CUSTOVERBA.DTAFINAL = TRUNC(SYSDATE)
   AND CASE
         WHEN NVL(MRL_CUSTOVERBA.INDSFAMILIA, 'N') = 'S' THEN
          (SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
             FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
            WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.SEQLOTE = X.SEQLOTE
              AND C.NROEMPRESA = X.NROEMPRESA
              AND C.CENTRALLOJA = X.CENTRALLOJA
              AND C.SEQVERBA = X.SEQVERBA
              AND C.SEQPRODUTO = X.SEQPRODUTO
              AND C.SEQAPURACAO IS NULL) +
          (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
            WHERE X.SEQLOTEFAMILIA = MRL_CUSTOVERBA.SEQLOTEFAMILIA
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQLOTE = X.SEQLOTE
              AND D.NROEMPRESA = X.NROEMPRESA
              AND D.CENTRALLOJA = X.CENTRALLOJA
              AND D.SEQVERBA = X.SEQVERBA
              AND D.SEQPRODUTO = X.SEQPRODUTO
              AND D.SEQAPURACAO IS NULL)
         WHEN NVL(MRL_CUSTOVERBA.INDSGRUPOPROD, 'N') = 'S' THEN
          (SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
             FROM MRL_LECUSTOVERBA C, MRL_CUSTOVERBA X
            WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.SEQLOTE = X.SEQLOTE
              AND C.NROEMPRESA = X.NROEMPRESA
              AND C.CENTRALLOJA = X.CENTRALLOJA
              AND C.SEQVERBA = X.SEQVERBA
              AND C.SEQPRODUTO = X.SEQPRODUTO
              AND C.SEQAPURACAO IS NULL) +
          (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E, MRL_CUSTOVERBA X
            WHERE X.SEQLOTE = MRL_CUSTOVERBA.SEQLOTE
              AND X.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQLOTE = X.SEQLOTE
              AND D.NROEMPRESA = X.NROEMPRESA
              AND D.CENTRALLOJA = X.CENTRALLOJA
              AND D.SEQVERBA = X.SEQVERBA
              AND D.SEQPRODUTO = X.SEQPRODUTO
              AND D.SEQAPURACAO IS NULL)
         ELSE
          (SELECT NVL(SUM(C.QTDUTILIZADAVERBA), 0)
             FROM MRL_LECUSTOVERBA C
            WHERE C.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
              AND C.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND C.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
              AND C.SEQVERBA = MRL_CUSTOVERBA.SEQVERBA
              AND C.SEQAPURACAO IS NULL) +
          (SELECT NVL(SUM(D.QTDUTILIZADAVERBA), 0)
             FROM MAD_PEDVENDAVERBA D, MAD_PEDVENDA E
            WHERE D.NROPEDVENDA = E.NROPEDVENDA
              AND D.NROEMPRESA = E.NROEMPRESA
              AND D.SEQPRODUTO = MRL_CUSTOVERBA.SEQPRODUTO
              AND D.NROEMPRESA = MRL_CUSTOVERBA.NROEMPRESA
              AND D.CENTRALLOJA = MRL_CUSTOVERBA.CENTRALLOJA
              AND D.SEQVERBA = MRL_CUSTOVERBA.SEQVERBA
              AND D.SEQAPURACAO IS NULL)
       END > 0

 ORDER BY MRL_CUSTOVERBA.SEQFORNECEDOR,
          MRL_CUSTOVERBA.NROEMPRESA,
          MAP_PRODUTO.DESCCOMPLETA
