CREATE OR REPLACE VIEW NAGV_APURACAO_CONTRATOS AS

-- View no DW
-- Apuracao Verbas - Dina
-- Giuliano 23/01/2025

SELECT TO_CHAR(N.DTAENTRADA, 'MM')  MES,
       TO_CHAR(N.DTAENTRADA, 'YYYY') ANO,
       TO_CHAR(NVL(ROUND(SUM(D.VLRDESCONTO), 2), 0), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''')  VLR_DESCONTO_CONTRATO

  FROM MGC_CONTRATO@LINK_C5 C,
       MLF_NOTAFISCAL@LINK_C5 N,
       MLF_NFITEM@LINK_C5 I,
       (SELECT SEQCONTRATODESCONTO,
               SEQCONTRATO,
               SEQAUXNOTAFISCAL,
               LINKERP,
               SEQITEMNF,
               ROUND(SUM(PERCENTUAL * VLTTOTALITEM / 100), 5) VLRDESCONTO -- RP 153233
          FROM MLF_DESCFINACONTRATO@LINK_C5
         GROUP BY SEQCONTRATO,
                  SEQAUXNOTAFISCAL,
                  LINKERP,
                  SEQITEMNF,
                  SEQCONTRATODESCONTO) D,
       GE_PESSOA@LINK_C5 P
 WHERE D.SEQCONTRATO = C.SEQCONTRATO
   AND N.SEQAUXNOTAFISCAL = D.SEQAUXNOTAFISCAL
   AND I.SEQAUXNOTAFISCAL = D.SEQAUXNOTAFISCAL
   AND P.SEQPESSOA = N.SEQPESSOA
   AND N.LINKERP = D.LINKERP
   AND I.SEQITEMNF = D.SEQITEMNF
   AND N.TIPNOTAFISCAL = 'E'
   AND EXISTS (SELECT 1
          FROM MGC_CONTRATODESCONTO@LINK_C5 A
         WHERE A.SEQCONTRATO = C.SEQCONTRATO)
 GROUP BY TO_CHAR(N.DTAENTRADA, 'MM')  ,
          TO_CHAR(N.DTAENTRADA, 'YYYY')
 ORDER BY 1
