CREATE OR REPLACE VIEW CONSINCO.NAGV_TEMPO_ENTREGA_CD AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/
       TO_CHAR(X.DTARECEBIMENTO, 'MM') MES,
       TO_CHAR(X.DTARECEBIMENTO, 'YYYY') ANO,
       --===============================================--
       -- Utiliza a Function para deduzir os domingos entre a diferenca de dias, em todas as medias
       -- Regra explicada dentro da Function NAGF_DEDUZ_DOMINGO_DTA
       --===============================================--
       -- Media Emissao Ped x Entrega na Loja
       -- Cross Docking pega DtaInclusao (certo?)
       ROUND(AVG((X.DTARECEBIMENTO - DECODE(K2.INDSELINVERSA,'S', P.DTAINCLUSAO, Z.DTAEMISSAO)) -
       CONSINCO.NAGF_DEDUZ_DOMINGO_DTA(X.DTARECEBIMENTO, DECODE(K2.INDSELINVERSA,'S', P.DTAINCLUSAO, Z.DTAEMISSAO))
       )) TP_MED_PED_REC,
       --===============================================--
       -- Media Emissao Ped x Faturamento
       ROUND(AVG((P.DTAGERACAONF - DECODE(K2.INDSELINVERSA,'S', P.DTAINCLUSAO, Z.DTAEMISSAO)) -
       CONSINCO.NAGF_DEDUZ_DOMINGO_DTA(P.DTAGERACAONF, DECODE(K2.INDSELINVERSA,'S', P.DTAINCLUSAO, Z.DTAEMISSAO))
       )) TP_MED_PED_FAT,
       --===============================================--
       -- Media Faturamento Venda Balcao x Entrega na Loja
       ROUND(AVG((X.DTARECEBIMENTO - P.DTAGERACAONF) -
       CONSINCO.NAGF_DEDUZ_DOMINGO_DTA(X.DTARECEBIMENTO, P.DTAGERACAONF)
       )) TP_MED_FAT_REC,
       --===============================================--
       ROUND((SUM((PI.QTDATENDIDA / PI.QTDEMBALAGEM) /
       EXTRACT(DAY FROM LAST_DAY(X.DTARECEBIMENTO))) / 1000)) QTD_MIL_FCD, ---DTARECEBIMENTO
       --===============================================--
       NVL(DECODE(K2.INDSELINVERSA,'S','Cross Docking', DECODE(C.TIPOLOTE,'T','Divisao Lote Manual','A','Abastacimento Automatico')),'Pedido Manual') TIPO

  FROM MLF_NOTAFISCAL X
       INNER JOIN MLF_NFITEM Y         ON X.SEQNF = Y.SEQNF
       INNER JOIN MSU_PSITEMRECEBIDO K ON K.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL AND K.SEQPRODUTO = Y.SEQPRODUTO AND X.NROEMPRESA = K.NROEMPRESA
       INNER JOIN MSU_PSITEMRECEBER K2 ON K2.NROPEDIDOSUPRIM = K.NROPEDIDOSUPRIM AND K2.NROEMPRESA = K.NROEMPRESA AND K2.SEQPRODUTO = K.SEQPRODUTO AND K2.CENTRALLOJA = K.CENTRALLOJA
       INNER JOIN MSU_PEDIDOSUPRIM Z   ON Z.NROPEDIDOSUPRIM = K.NROPEDIDOSUPRIM AND Z.NROEMPRESA = K.NROEMPRESA AND Z.CENTRALLOJA = K.CENTRALLOJA
       INNER JOIN MAD_PEDVENDAITEM PI  ON PI.NUMERODF = X.NUMERONF AND PI.SERIEDF = X.SERIENF AND PI.NROEMPRESA = X.SEQPESSOA AND PI.SEQPRODUTO = Y.SEQPRODUTO
       INNER JOIN MAD_PEDVENDA     P   ON P.NROPEDVENDA = PI.NROPEDVENDA AND P.NROEMPRESA = PI.NROEMPRESA
       INNER JOIN MAC_GERCOMPRA    C   ON C.SEQGERCOMPRA = Z.SEQGERCOMPRA

 WHERE EXISTS (SELECT 1 FROM DWNAGT_DADOSEMPRESA@BI Z WHERE Z.TIPO = 'CD' AND Z.NROEMPRESA = X.SEQPESSOA)
   AND EXISTS (SELECT 1 FROM MAX_CODGERALOPER C WHERE C.TIPUSO = 'R' AND C.CODGERALOPER = X.CODGERALOPER)

   AND 1=1
   --AND X.DTARECEBIMENTO BETWEEN DATE '2023-12-01' AND DATE '2023-12-31'
   AND X.STATUSNF = 'V'
   AND (C.TIPOLOTE IN ('T','A') OR K2.INDSELINVERSA = 'S')

GROUP BY TO_CHAR(X.DTARECEBIMENTO, 'MM'),
         TO_CHAR(X.DTARECEBIMENTO, 'YYYY'),
         EXTRACT(DAY FROM LAST_DAY(DTARECEBIMENTO)),
         NVL(DECODE(K2.INDSELINVERSA,'S','Cross Docking', DECODE(C.TIPOLOTE,'T','Divisao Lote Manual','A','Abastacimento Automatico')),'Pedido Manual')

ORDER BY 2, 1
;
