CREATE OR REPLACE VIEW CONSINCO.NAGV_BASE_BENEFICIOS AS

SELECT X.SEQPESSOA, X.SEQPESSOA||' - '||G.NOMERAZAO PESSOA, D.DESCRICAO DEPOSITARIO, NROEMPRESA,
       NROTITULO||'-'||X.SERIETITULO||'/'||X.NROPARCELA TITULO, X.DTAEMISSAO,  
       TO_CHAR(DTAEMISSAO, 'YYYY') ANO,
	     TO_CHAR(DTAEMISSAO, 'MM') MES,
       X.DTAPROGRAMADA, X.VLRORIGINAL VALOR

  FROM FI_TITULO X INNER JOIN GE_PESSOA G ON X.SEQPESSOA = G.SEQPESSOA
                   INNER JOIN FI_DEPOSITARIO D ON D.SEQDEPOSITARIO = X.SEQDEPOSITARIO

 WHERE X.SEQPESSOA IN (662721,752977,130514,1017807,1301560,2653466,117039) -- Filtros enviados pelo RH

   AND X.ABERTOQUITADO = 'Q' -- Somente quitados
   AND D.SEQDEPOSITARIO = 2
   AND X.SITUACAO != 'C'  
;
