CREATE OR REPLACE VIEW CONSINCO.NAGV_BUSCADTAPEDIDO AS
SELECT SEQLOTEMODELO,
       TO_DATE(CONSINCO.NAGF_BUSCAULTDTAPEDIDO(X.SEQLOTEMODELO), 'DD/MM/YY') DATA_VALIDA,
       NVL(X.HORAMIN, '01:00') HORAMIN, X.DIASEMANA

  FROM CONSINCO.NAGT_CONTROLELOTECOMPRA X
 WHERE CONSINCO.NAGF_BUSCAULTDTAPEDIDO(X.SEQLOTEMODELO) IS NOT NULL

  ORDER BY 2 ASC;
