CREATE OR REPLACE TRIGGER TBU_MAP_PRODUTO_AUD
BEFORE UPDATE ON MAP_PRODUTO
FOR EACH ROW
DECLARE
 vnLoteAuditoria NUMBER;
 vsPDAudProduto varchar2(1);
BEGIN
  sp_buscaparamdinamico('PRODUTO',0,'UTIL_AUD_PRODUTO','S','N', 'UTILIZA CONTROLE DE ALTERAÇÕES NO CADASTRO DE PRODUTO ?',vsPDAudProduto);
  IF vsPDAudProduto = 'S' THEN
    SELECT S_LOTEAUDITORIA.NEXTVAL
      INTO vnLoteAuditoria
      FROM DUAL;
    IF :OLD.INDEMITECODPRODFISCALNFE !=  :NEW.INDEMITECODPRODFISCALNFE  OR (:OLD.INDEMITECODPRODFISCALNFE IS NULL AND  :NEW.INDEMITECODPRODFISCALNFE IS NOT NULL ) OR (:OLD.INDEMITECODPRODFISCALNFE IS NOT NULL AND  :NEW.INDEMITECODPRODFISCALNFE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDEMITECODPRODFISCALNFE','Emite Cod. Prod. Fiscal na NFe', :OLD.INDEMITECODPRODFISCALNFE, :NEW.INDEMITECODPRODFISCALNFE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PERCDIASADVERRECBTO !=  :NEW.PERCDIASADVERRECBTO  OR (:OLD.PERCDIASADVERRECBTO IS NULL AND  :NEW.PERCDIASADVERRECBTO IS NOT NULL ) OR (:OLD.PERCDIASADVERRECBTO IS NOT NULL AND  :NEW.PERCDIASADVERRECBTO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PERCDIASADVERRECBTO','Percentual para advertência de recebimento', :OLD.PERCDIASADVERRECBTO, :NEW.PERCDIASADVERRECBTO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.CODIGOANP !=  :NEW.CODIGOANP  OR (:OLD.CODIGOANP IS NULL AND  :NEW.CODIGOANP IS NOT NULL ) OR (:OLD.CODIGOANP IS NOT NULL AND  :NEW.CODIGOANP IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'CODIGOANP','Código ANP', :OLD.CODIGOANP, :NEW.CODIGOANP,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.CODIGOIF !=  :NEW.CODIGOIF  OR (:OLD.CODIGOIF IS NULL AND  :NEW.CODIGOIF IS NOT NULL ) OR (:OLD.CODIGOIF IS NOT NULL AND  :NEW.CODIGOIF IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'CODIGOIF','CODIF', :OLD.CODIGOIF, :NEW.CODIGOIF,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDINTEGRAECOMMERCE !=  :NEW.INDINTEGRAECOMMERCE  OR (:OLD.INDINTEGRAECOMMERCE IS NULL AND  :NEW.INDINTEGRAECOMMERCE IS NOT NULL ) OR (:OLD.INDINTEGRAECOMMERCE IS NOT NULL AND  :NEW.INDINTEGRAECOMMERCE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDINTEGRAECOMMERCE','E-Commerce\Integra Produto com E-Commerce', :OLD.INDINTEGRAECOMMERCE, :NEW.INDINTEGRAECOMMERCE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.QTDLIMITEPROMOCECOMMERCE !=  :NEW.QTDLIMITEPROMOCECOMMERCE  OR (:OLD.QTDLIMITEPROMOCECOMMERCE IS NULL AND  :NEW.QTDLIMITEPROMOCECOMMERCE IS NOT NULL ) OR (:OLD.QTDLIMITEPROMOCECOMMERCE IS NOT NULL AND  :NEW.QTDLIMITEPROMOCECOMMERCE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'QTDLIMITEPROMOCECOMMERCE','E-Commerce\Quantidade Limite para Promoção', :OLD.QTDLIMITEPROMOCECOMMERCE, :NEW.QTDLIMITEPROMOCECOMMERCE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.YOUTUBECODEECOMMERCE !=  :NEW.YOUTUBECODEECOMMERCE  OR (:OLD.YOUTUBECODEECOMMERCE IS NULL AND  :NEW.YOUTUBECODEECOMMERCE IS NOT NULL ) OR (:OLD.YOUTUBECODEECOMMERCE IS NOT NULL AND  :NEW.YOUTUBECODEECOMMERCE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'YOUTUBECODEECOMMERCE','E-Commerce\YouTube Code', :OLD.YOUTUBECODEECOMMERCE, :NEW.YOUTUBECODEECOMMERCE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.DATAHORINTEGRACAOECOMMERCE !=  :NEW.DATAHORINTEGRACAOECOMMERCE  OR (:OLD.DATAHORINTEGRACAOECOMMERCE IS NULL AND  :NEW.DATAHORINTEGRACAOECOMMERCE IS NOT NULL ) OR (:OLD.DATAHORINTEGRACAOECOMMERCE IS NOT NULL AND  :NEW.DATAHORINTEGRACAOECOMMERCE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'DATAHORINTEGRACAOECOMMERCE','E-Commerce\Data de Integração com E-Commerce', :OLD.DATAHORINTEGRACAOECOMMERCE, :NEW.DATAHORINTEGRACAOECOMMERCE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDRES3166 !=  :NEW.INDRES3166  OR (:OLD.INDRES3166 IS NULL AND  :NEW.INDRES3166 IS NOT NULL ) OR (:OLD.INDRES3166 IS NOT NULL AND  :NEW.INDRES3166 IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDRES3166','Resolução 3166', :OLD.INDRES3166, :NEW.INDRES3166,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.SEQFAMILIA !=  :NEW.SEQFAMILIA  OR (:OLD.SEQFAMILIA IS NULL AND  :NEW.SEQFAMILIA IS NOT NULL ) OR (:OLD.SEQFAMILIA IS NOT NULL AND  :NEW.SEQFAMILIA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'SEQFAMILIA','Familia', :OLD.SEQFAMILIA, :NEW.SEQFAMILIA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.COMPLEMENTO !=  :NEW.COMPLEMENTO  OR (:OLD.COMPLEMENTO IS NULL AND  :NEW.COMPLEMENTO IS NOT NULL ) OR (:OLD.COMPLEMENTO IS NOT NULL AND  :NEW.COMPLEMENTO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'COMPLEMENTO','Complemento', :OLD.COMPLEMENTO, :NEW.COMPLEMENTO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.DESCCOMPLETA !=  :NEW.DESCCOMPLETA  OR (:OLD.DESCCOMPLETA IS NULL AND  :NEW.DESCCOMPLETA IS NOT NULL ) OR (:OLD.DESCCOMPLETA IS NOT NULL AND  :NEW.DESCCOMPLETA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'DESCCOMPLETA','Descrição', :OLD.DESCCOMPLETA, :NEW.DESCCOMPLETA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.DESCREDUZIDA !=  :NEW.DESCREDUZIDA  OR (:OLD.DESCREDUZIDA IS NULL AND  :NEW.DESCREDUZIDA IS NOT NULL ) OR (:OLD.DESCREDUZIDA IS NOT NULL AND  :NEW.DESCREDUZIDA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'DESCREDUZIDA','Descrição Reduzida', :OLD.DESCREDUZIDA, :NEW.DESCREDUZIDA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.REFFABRICANTE !=  :NEW.REFFABRICANTE  OR (:OLD.REFFABRICANTE IS NULL AND  :NEW.REFFABRICANTE IS NOT NULL ) OR (:OLD.REFFABRICANTE IS NOT NULL AND  :NEW.REFFABRICANTE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'REFFABRICANTE','Referência Fabricante', :OLD.REFFABRICANTE, :NEW.REFFABRICANTE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.ESPECIFICDETALHADA !=  :NEW.ESPECIFICDETALHADA  OR (:OLD.ESPECIFICDETALHADA IS NULL AND  :NEW.ESPECIFICDETALHADA IS NOT NULL ) OR (:OLD.ESPECIFICDETALHADA IS NOT NULL AND  :NEW.ESPECIFICDETALHADA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'ESPECIFICDETALHADA','Especificação Detalhada', :OLD.ESPECIFICDETALHADA, :NEW.ESPECIFICDETALHADA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.DESCCOMPOSICAO !=  :NEW.DESCCOMPOSICAO  OR (:OLD.DESCCOMPOSICAO IS NULL AND  :NEW.DESCCOMPOSICAO IS NOT NULL ) OR (:OLD.DESCCOMPOSICAO IS NOT NULL AND  :NEW.DESCCOMPOSICAO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'DESCCOMPOSICAO','Descrição Composição', :OLD.DESCCOMPOSICAO, :NEW.DESCCOMPOSICAO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PZOVALIDADEDIA !=  :NEW.PZOVALIDADEDIA  OR (:OLD.PZOVALIDADEDIA IS NULL AND  :NEW.PZOVALIDADEDIA IS NOT NULL ) OR (:OLD.PZOVALIDADEDIA IS NOT NULL AND  :NEW.PZOVALIDADEDIA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PZOVALIDADEDIA','Prazo Validade Recebimento', :OLD.PZOVALIDADEDIA, :NEW.PZOVALIDADEDIA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PROPQTDPERDAAUTO !=  :NEW.PROPQTDPERDAAUTO  OR (:OLD.PROPQTDPERDAAUTO IS NULL AND  :NEW.PROPQTDPERDAAUTO IS NOT NULL ) OR (:OLD.PROPQTDPERDAAUTO IS NOT NULL AND  :NEW.PROPQTDPERDAAUTO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PROPQTDPERDAAUTO','Proporção Perda Automática', :OLD.PROPQTDPERDAAUTO, :NEW.PROPQTDPERDAAUTO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PZOVALIDADEDIASAIDA !=  :NEW.PZOVALIDADEDIASAIDA  OR (:OLD.PZOVALIDADEDIASAIDA IS NULL AND  :NEW.PZOVALIDADEDIASAIDA IS NOT NULL ) OR (:OLD.PZOVALIDADEDIASAIDA IS NOT NULL AND  :NEW.PZOVALIDADEDIASAIDA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PZOVALIDADEDIASAIDA','Prazo Validade Saida', :OLD.PZOVALIDADEDIASAIDA, :NEW.PZOVALIDADEDIASAIDA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDPROCFABRICACAO !=  :NEW.INDPROCFABRICACAO  OR (:OLD.INDPROCFABRICACAO IS NULL AND  :NEW.INDPROCFABRICACAO IS NOT NULL ) OR (:OLD.INDPROCFABRICACAO IS NOT NULL AND  :NEW.INDPROCFABRICACAO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDPROCFABRICACAO','Processo Fabricação Própria', :OLD.INDPROCFABRICACAO, :NEW.INDPROCFABRICACAO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.QTDFABRICADALOTE !=  :NEW.QTDFABRICADALOTE  OR (:OLD.QTDFABRICADALOTE IS NULL AND  :NEW.QTDFABRICADALOTE IS NOT NULL ) OR (:OLD.QTDFABRICADALOTE IS NOT NULL AND  :NEW.QTDFABRICADALOTE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'QTDFABRICADALOTE','Quantidade por Lote', :OLD.QTDFABRICADALOTE, :NEW.QTDFABRICADALOTE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.SEQPRODUTOBASE !=  :NEW.SEQPRODUTOBASE  OR (:OLD.SEQPRODUTOBASE IS NULL AND  :NEW.SEQPRODUTOBASE IS NOT NULL ) OR (:OLD.SEQPRODUTOBASE IS NOT NULL AND  :NEW.SEQPRODUTOBASE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'SEQPRODUTOBASE','Produto Base', :OLD.SEQPRODUTOBASE, :NEW.SEQPRODUTOBASE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PERCACRESPRECO !=  :NEW.PERCACRESPRECO  OR (:OLD.PERCACRESPRECO IS NULL AND  :NEW.PERCACRESPRECO IS NOT NULL ) OR (:OLD.PERCACRESPRECO IS NOT NULL AND  :NEW.PERCACRESPRECO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PERCACRESPRECO','% Acréscimo Preço', :OLD.PERCACRESPRECO, :NEW.PERCACRESPRECO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDPRECOZEROBALANCA !=  :NEW.INDPRECOZEROBALANCA  OR (:OLD.INDPRECOZEROBALANCA IS NULL AND  :NEW.INDPRECOZEROBALANCA IS NOT NULL ) OR (:OLD.INDPRECOZEROBALANCA IS NOT NULL AND  :NEW.INDPRECOZEROBALANCA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDPRECOZEROBALANCA','Gera Preço Zero para Balanças', :OLD.INDPRECOZEROBALANCA, :NEW.INDPRECOZEROBALANCA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.FATORCONVERSAO !=  :NEW.FATORCONVERSAO  OR (:OLD.FATORCONVERSAO IS NULL AND  :NEW.FATORCONVERSAO IS NOT NULL ) OR (:OLD.FATORCONVERSAO IS NOT NULL AND  :NEW.FATORCONVERSAO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'FATORCONVERSAO','FATORCONVERSAO', :OLD.FATORCONVERSAO, :NEW.FATORCONVERSAO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PZOVALIDADEMES !=  :NEW.PZOVALIDADEMES  OR (:OLD.PZOVALIDADEMES IS NULL AND  :NEW.PZOVALIDADEMES IS NOT NULL ) OR (:OLD.PZOVALIDADEMES IS NOT NULL AND  :NEW.PZOVALIDADEMES IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PZOVALIDADEMES','Nro de Meses de Validade', :OLD.PZOVALIDADEMES, :NEW.PZOVALIDADEMES,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.NROREGMINSAUDE !=  :NEW.NROREGMINSAUDE  OR (:OLD.NROREGMINSAUDE IS NULL AND  :NEW.NROREGMINSAUDE IS NOT NULL ) OR (:OLD.NROREGMINSAUDE IS NOT NULL AND  :NEW.NROREGMINSAUDE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'NROREGMINSAUDE','Nro Reg Ministério da Saúde', :OLD.NROREGMINSAUDE, :NEW.NROREGMINSAUDE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.CODPRODFISCAL !=  :NEW.CODPRODFISCAL  OR (:OLD.CODPRODFISCAL IS NULL AND  :NEW.CODPRODFISCAL IS NOT NULL ) OR (:OLD.CODPRODFISCAL IS NOT NULL AND  :NEW.CODPRODFISCAL IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'CODPRODFISCAL','Código Integração Sistema Fiscal', :OLD.CODPRODFISCAL, :NEW.CODPRODFISCAL,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.DESCGENERICA !=  :NEW.DESCGENERICA  OR (:OLD.DESCGENERICA IS NULL AND  :NEW.DESCGENERICA IS NOT NULL ) OR (:OLD.DESCGENERICA IS NOT NULL AND  :NEW.DESCGENERICA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'DESCGENERICA','Descrição Genérica', :OLD.DESCGENERICA, :NEW.DESCGENERICA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PROPQTDPRODUTOBASE !=  :NEW.PROPQTDPRODUTOBASE  OR (:OLD.PROPQTDPRODUTOBASE IS NULL AND  :NEW.PROPQTDPRODUTOBASE IS NOT NULL ) OR (:OLD.PROPQTDPRODUTOBASE IS NOT NULL AND  :NEW.PROPQTDPRODUTOBASE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PROPQTDPRODUTOBASE','Proporção de Baixa do Produto Base', :OLD.PROPQTDPRODUTOBASE, :NEW.PROPQTDPRODUTOBASE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.NRODIASADVERRECBTO !=  :NEW.NRODIASADVERRECBTO  OR (:OLD.NRODIASADVERRECBTO IS NULL AND  :NEW.NRODIASADVERRECBTO IS NOT NULL ) OR (:OLD.NRODIASADVERRECBTO IS NOT NULL AND  :NEW.NRODIASADVERRECBTO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'NRODIASADVERRECBTO','Nro de dias para advertência de recebimento', :OLD.NRODIASADVERRECBTO, :NEW.NRODIASADVERRECBTO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PERCALTPRECRELAC !=  :NEW.PERCALTPRECRELAC  OR (:OLD.PERCALTPRECRELAC IS NULL AND  :NEW.PERCALTPRECRELAC IS NOT NULL ) OR (:OLD.PERCALTPRECRELAC IS NOT NULL AND  :NEW.PERCALTPRECRELAC IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PERCALTPRECRELAC','% Variação Alteração Preço Prod.Relacionado', :OLD.PERCALTPRECRELAC, :NEW.PERCALTPRECRELAC,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.NROITEMFIXO !=  :NEW.NROITEMFIXO  OR (:OLD.NROITEMFIXO IS NULL AND  :NEW.NROITEMFIXO IS NOT NULL ) OR (:OLD.NROITEMFIXO IS NOT NULL AND  :NEW.NROITEMFIXO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'NROITEMFIXO','Nro item fixo Nota Fiscal', :OLD.NROITEMFIXO, :NEW.NROITEMFIXO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.GERALIVROCPROD !=  :NEW.GERALIVROCPROD  OR (:OLD.GERALIVROCPROD IS NULL AND  :NEW.GERALIVROCPROD IS NOT NULL ) OR (:OLD.GERALIVROCPROD IS NOT NULL AND  :NEW.GERALIVROCPROD IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'GERALIVROCPROD','Participa Controle Produção Estoque', :OLD.GERALIVROCPROD, :NEW.GERALIVROCPROD,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDUSANFDESPESA !=  :NEW.INDUSANFDESPESA  OR (:OLD.INDUSANFDESPESA IS NULL AND  :NEW.INDUSANFDESPESA IS NOT NULL ) OR (:OLD.INDUSANFDESPESA IS NOT NULL AND  :NEW.INDUSANFDESPESA IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDUSANFDESPESA','Usa Produto na Nota Fiscal de Despesa', :OLD.INDUSANFDESPESA, :NEW.INDUSANFDESPESA,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.SEQBULARIO !=  :NEW.SEQBULARIO  OR (:OLD.SEQBULARIO IS NULL AND  :NEW.SEQBULARIO IS NOT NULL ) OR (:OLD.SEQBULARIO IS NOT NULL AND  :NEW.SEQBULARIO IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'SEQBULARIO','Medicamentos\Bulário', :OLD.SEQBULARIO, :NEW.SEQBULARIO,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDREPLICAINFOFORNEC !=  :NEW.INDREPLICAINFOFORNEC  OR (:OLD.INDREPLICAINFOFORNEC IS NULL AND  :NEW.INDREPLICAINFOFORNEC IS NOT NULL ) OR (:OLD.INDREPLICAINFOFORNEC IS NOT NULL AND  :NEW.INDREPLICAINFOFORNEC IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDREPLICAINFOFORNEC','Replica as manutenções da aba fornecedor para as demais empresas no cadastro de produto', :OLD.INDREPLICAINFOFORNEC, :NEW.INDREPLICAINFOFORNEC,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.INDPARTCOTATAC !=  :NEW.INDPARTCOTATAC OR (:OLD.INDPARTCOTATAC IS NULL AND  :NEW.INDPARTCOTATAC IS NOT NULL ) OR (:OLD.INDPARTCOTATAC IS NOT NULL AND  :NEW.INDPARTCOTATAC IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'INDPARTCOTATAC','Participação frequente em cotações atacadistas', :OLD.INDPARTCOTATAC, :NEW.INDPARTCOTATAC,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PERCACRESCCUSTORELAC !=  :NEW.PERCACRESCCUSTORELAC  OR (:OLD.PERCACRESCCUSTORELAC IS NULL AND  :NEW.PERCACRESCCUSTORELAC IS NOT NULL ) OR (:OLD.PERCACRESCCUSTORELAC IS NOT NULL AND  :NEW.PERCACRESCCUSTORELAC IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PERCACRESCCUSTORELAC','fator Custo prod.base', :OLD.PERCACRESCCUSTORELAC, :NEW.PERCACRESCCUSTORELAC,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PERCACRESCCUSTORELACVIG !=  :NEW.PERCACRESCCUSTORELACVIG  OR (:OLD.PERCACRESCCUSTORELACVIG IS NULL AND  :NEW.PERCACRESCCUSTORELACVIG IS NOT NULL ) OR (:OLD.PERCACRESCCUSTORELACVIG IS NOT NULL AND  :NEW.PERCACRESCCUSTORELACVIG IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PERCACRESCCUSTORELACVIG','fator Custo prod.base', :OLD.PERCACRESCCUSTORELACVIG, :NEW.PERCACRESCCUSTORELACVIG,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.PZOVALIDLOTE  !=  :NEW.PZOVALIDLOTE   OR (:OLD.PZOVALIDLOTE  IS NULL AND  :NEW.PZOVALIDLOTE  IS NOT NULL ) OR (:OLD.PZOVALIDLOTE  IS NOT NULL AND  :NEW.PZOVALIDLOTE  IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'PZOVALIDLOTE','Default prazo de validade do lote', :OLD.PZOVALIDLOTE, :NEW.PZOVALIDLOTE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.SEQPRODRELACLOTE  !=  :NEW.SEQPRODRELACLOTE   OR (:OLD.SEQPRODRELACLOTE  IS NULL AND  :NEW.SEQPRODRELACLOTE  IS NOT NULL ) OR (:OLD.SEQPRODRELACLOTE  IS NOT NULL AND  :NEW.SEQPRODRELACLOTE  IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'SEQPRODRELACLOTE','Produto relac. lote', :OLD.SEQPRODRELACLOTE, :NEW.SEQPRODRELACLOTE,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.ALIQADJUD !=  :NEW.ALIQADJUD  OR (:OLD.ALIQADJUD IS NULL AND  :NEW.ALIQADJUD IS NOT NULL ) OR (:OLD.ALIQADJUD IS NOT NULL AND  :NEW.ALIQADJUD IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'ALIQADJUD','Alíquota de Adjudicação', :OLD.ALIQADJUD, :NEW.ALIQADJUD,vnLoteAuditoria,'Produto');
    END IF;
    --
    IF :OLD.MOTIVOISENCAOMINSAUDE !=  :NEW.MOTIVOISENCAOMINSAUDE  OR (:OLD.MOTIVOISENCAOMINSAUDE IS NULL AND :NEW.MOTIVOISENCAOMINSAUDE IS NOT NULL ) OR (:OLD.MOTIVOISENCAOMINSAUDE IS NOT NULL AND  :NEW.MOTIVOISENCAOMINSAUDE IS NULL )   THEN
      INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),:NEW.USUARIOALTERACAO, :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'MOTIVOISENCAOMINSAUDE','Motivo da isenção da ANVISA', :OLD.MOTIVOISENCAOMINSAUDE, :NEW.MOTIVOISENCAOMINSAUDE,vnLoteAuditoria,'Produto');
    END IF;
    -- Giuliano 21/05/24 - Salvar Log OBSENCARTE
    IF :OLD.OBSENCARTE != :NEW.OBSENCARTE OR (:OLD.OBSENCARTE IS NULL AND :NEW.OBSENCARTE IS NOT NULL ) OR (:OLD.OBSENCARTE IS NOT NULL AND  :NEW.OBSENCARTE IS NULL ) THEN
    INSERT INTO MAP_AUDITORIA
      (SEQAUDITORIA, DTAHORAUDITORIA, DTAAUDITORIA, USUAUDITORIA, SEQIDENTIFICA, TABELA, ORIGEM , CAMPO,DESCCAMPO, VLRANTERIOR, VLRATUAL,LOTEAUDITORIA,IDENTIFICADOR)
      VALUES (S_SEQAUDITORIA.NEXTVAL, SYSDATE, TRUNC(SYSDATE),(SELECT SYS_CONTEXT ('USERENV','CLIENT_IDENTIFIER')FROM DUAL), :NEW.SEQPRODUTO, 'MAP_PRODUTO','PRODUTO' , 'OBSENCARTE','Observação do Encarte', :OLD.OBSENCARTE, :NEW.OBSENCARTE,vnLoteAuditoria,'Produto');
    END IF;
    
    --
  END IF;
  exception
    when others then
      raise_application_error(-20200, sqlerrm);
END;
